/**
 * constants 的「identity-onboarding」部分（09-22 从同目录 constants.tsx 按顶层声明分出，纯搬迁、零改写）。
 * ⛔ 逻辑与原地逐字一致，只补了顶部 import 与 `export`。
 */
import {
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowUp,
  ArrowUpRight,
  Bot,
  Brain,
  QrCode,
  Star,
  Check,
  ChevronDown,
  CircleGauge,
  Clock3,
  TriangleAlert,
  CircleStop,
  Cloud,
  CloudOff,
  Code2,
  Copy,
  Eye,
  EyeOff,
  Edit3,
  FileCode2,
  FileText,
  FileWarning,
  FolderOpen,
  FolderPlus,
  FolderTree,
  ImagePlus,
  Image,
  GitBranch,
  Globe2,
  GripVertical,
  Hash,
  Info,
  KeyRound,
  LayoutGrid,
  Layers3,
  Link2,
  ListFilter,
  Maximize2,
  Megaphone,
  Menu,
  BarChart3,
  PenTool,
  MessageSquare,
  MessageSquarePlus,
  Monitor,
  Moon,
  MoreHorizontal,
  Plus,
  Quote,
  Paperclip,
  PanelLeftClose,
  PanelRightClose,
  PanelRightOpen,
  PenLine,
  Play,
  PowerOff,
  RefreshCw,
  ArrowLeft,
  ArrowRight,
  Download,
  Upload,
  Search,
  Send,
  Settings2,
  Shield,
  Smartphone,
  ShieldCheck,
  Sparkles,
  Store,
  TerminalSquare,
  Target,
  Trash2,
  Type,
  Sun,
  User,
  Wrench,
  Wifi,
  X,
  ChevronUp,
  FileUp,
  Minimize2,
  Zap,
  MonitorUp,
  BookOpen,
  BookmarkPlus,
  Home,
  Lock,
  CircleCheck,
  CircleX,
  ZoomIn,
  ZoomOut,
  ListRestart,
  Keyboard,
  Server,
  WifiOff,
  UserRound,
  Rocket,
  BookMarked,
  Users,
  ListChecks,
  LoaderCircle,
  GitPullRequest,
  ShieldAlert,
  RotateCcw,
  Briefcase,
  Tag,
  Workflow,
  LogOut,
  ChevronRight,
  ChevronLeft,
  ExternalLink,
  Pin,
  Wallet,
  LogIn,
  Database,
  Headphones,
  Mic,
  Pause,
  FileQuestion,
  ClipboardList,
  DraftingCompass,
  FlaskConical,
  Crown,
  TrendingUp,
  Microscope,
  Calculator,
  Telescope,
  CircleHelp,
  Video,
  Bell,
  CheckCheck,
} from "lucide-react";
import {
  ponytailSubSkills, planAction, applyAction, isEmptyAction, describePartial, guardOffOwner,
  findCapabilitySkill, findCapabilitySkills, syncedSnapshot, samePluginId,
  PONYTAIL_PLUGIN_ID, NUPHUS_MCP_ID, DESKTOP_SKILL_ID, BROWSER_SKILL_ID, BROWSER_SKILL_IDS, GROUP_LABELS,
  type CapabilityGroupId, type SubToggleSnapshot, type GroupIpc, type MemberKey,
} from "../../../lib/capability-groups";
export /** 统一复制入口：首选主进程 electron clipboard（不受渲染层 Clipboard API 的
 *  焦点/权限限制——用户实测窗口失焦时 navigator.clipboard.writeText 抛
 *  "Write permission denied"），旧构建没有该 IPC 或再失败时回落浏览器 API，
 *  最后用隐藏 textarea + execCommand 兜底（http 环境/老内核）。 */

/** 首次对话身份引导：随新会话的 thread/start developerInstructions 注入（引擎每会话
 *  全新读入，天然「每个新会话初次对话生效」）。引导收集的信息由 identity_onboard 工具
 *  落盘（personalization.json），onboarded=true 后新会话不再注入——已配置就不再引导。 */
const IDENTITY_ONBOARD_INSTRUCTIONS = [
  "【初次见面（第一条回复就把招呼和提问全部完成）】这是你与用户的第一次对话。你的第一条回复必须是一段热情自然的欢迎词，其中一次性完成：",
  "1. 打招呼 + 介绍自己还没有名字，请用户给你取一个（取不取都行）；",
  "2. 用聊天的语气（不是编号问卷！）把想了解的事自然地问全：平时想让你帮什么忙（写代码/自动化/数据/写作…）、希望怎么称呼 TA、TA 的职业或常用技术栈、喜欢什么样的回复（简洁要点还是详细解释、轻松还是专业）、爱好兴趣、有没有想让你长期记住的习惯（比如「直接指出我的错误」）；",
  "3. 结尾轻描淡写补一句：不想答的跳过就行，先聊正事也完全没问题。",
  "用户回复后：从 TA 的话里提取各维度信息，**立刻调用 identity_onboard 工具一次性保存**（没聊到的维度传空字符串，绝不编造；用户给取了名字务必带上）。保存后热情确认一句（取了名字就正式认下这个名字），然后立刻回归正常、简洁的工作风格——不再发起第二轮提问，正事随叫随到。",
].join("\n");

export const IDENTITY_ONBOARD_TOOL = {
  type: "function",
  name: "identity_onboard",
  description: "保存初次见面引导收集的用户中心信息（所有字段可选，没聊到的传空字符串）。调用后引导结束，后续会话不再引导。",
  inputSchema: {
    type: "object",
    properties: {
      assistantName: { type: "string", description: "用户给 Codex 取的名字；没取则传空字符串" },
      userName: { type: "string", description: "用户希望被称呼的名字；未提供则传空字符串" },
      about: { type: "string", description: "用户的主要使用场景/手头项目，一句话" },
      occupation: { type: "string", description: "职业/技术栈/常用语言" },
      replyStyle: { type: "string", description: "回复风格偏好（如：简洁要点/详细解释/代码优先/结论先行）" },
      tone: { type: "string", description: "语气偏好（如：轻松幽默/专业中性/热情）" },
      interests: { type: "string", description: "爱好与兴趣，自由文本" },
      habits: { type: "string", description: "其它想被长期记住的偏好或习惯（如：直接指出错误、别主动建议）" },
    },
  },
};

export /** 行业分类 ID → 中文名（与专家团编辑器一致） */
const EXPERT_CATEGORY_LABELS: Record<string, string> = {
  "01-ProductDesign": "产品设计", "02-Engineering": "技术工程", "03-GameSpatial": "游戏空间",
  "04-DataAI": "数据智能", "05-MarketingGrowth": "营销增长", "06-ContentCreative": "内容创作",
  "07-SalesCommerce": "销售商务", "08-FinanceInvestment": "金融投资", "09-OperationsHR": "运营人力",
  "10-ProjectQuality": "项目质量", "11-SecurityCompliance": "法务安全", "12-IndustryConsultant": "行业顾问",
};

export /** 按职业头衔/名字映射专家头像图标（专家中心卡与成员 chip 共用，替代千篇一律的首字色块） */

/** 专家中心分类：按领域分组陈列，让用户一眼看清每个专家是干嘛的；未归类的团队落「更多专家」。 */
const EXPERT_CATEGORY_DEFS = [
  { title: "研发交付", blurb: "需求 → 架构 → 编码 → 测试，全流程软件交付", icon: Code2, teamIds: ["software-dev-team"] },
  { title: "投资交易", blurb: "行情策略、资金分析、估值定价与风控", icon: TrendingUp, teamIds: ["trading-analysis-team"] },
  { title: "内容创作", blurb: "文案策划、编辑润色、视觉设计与校对质检", icon: PenTool, teamIds: ["content-creation-team"] },
  { title: "数据分析", blurb: "数据工程、统计分析、可视化与业务洞察", icon: BarChart3, teamIds: ["data-analysis-team"] },
  { title: "市场增长", blurb: "市场策略、内容营销、投放优化与增长分析", icon: Megaphone, teamIds: ["marketing-growth-team"] },
  { title: "产品设计", blurb: "用户研究、产品策略与 UI/UX 设计", icon: DraftingCompass, teamIds: ["product-design-team"] },
  { title: "专项专家", blurb: "开箱即用的独立单人专家", icon: Sparkles, teamIds: ["zhiwei-content-oracle", "chengxiang-ppt-master", "dongming-code-review"] },
];

export const MEMORY_CATEGORIES = [
  { name: "用户纠错", icon: TriangleAlert, hint: "用户明确说你做错了/不满意 —— 单独一类，注入最前、永不淘汰" },
  { name: "用户偏好", icon: User, hint: "用户风格、口味、习惯、长期偏好" },
  { name: "项目背景", icon: BookOpen, hint: "项目定位、模块、关键约束" },
  { name: "工作流/SOP", icon: ListFilter, hint: "固定的流程、约定、复盘准则" },
  { name: "任务经验", icon: Brain, hint: "踩过的坑、有效解法、可复用经验" },
  { name: "临时上下文", icon: Clock3, hint: "临时记录,任务结束后清理" },
] as const;

export /** 能力总闸各子项在提示文案里的展示名（describePartial / 部分启用提示用）。 */
const MEMBER_LABELS: Partial<Record<MemberKey, string>> = {
  ponytail: "ponytail 注入开关",
  ponytailPlugin: "ponytail 插件",
  ponytailSkills: "ponytail 子技能",
  desktop: "桌面自动化总闸",
  nuphusMcp: "nuphus MCP",
  desktopSkill: `${DESKTOP_SKILL_ID} 技能`,
  browser: "浏览器自动化总闸",
  browserSkill: "浏览器自动化技能",
};
