/* ⛔ 自动生成，请勿手改 —— 生成器：`node scripts/gen-codex-official-catalog.mjs`（需联网）
 * 数据源：github.com/openai/plugins@main 的 .agents/plugins/{marketplace,api_marketplace}.json
 *         与各插件的 plugins/<slug>/.codex-plugin/plugin.json（简介 = 上游首句逐字截断，未改写）
 * 抓取时间：2026-10-03　共 65 个条目（其中 3 个无本地 manifest：外部仓库源）
 * ⛔ 运行时仍以 marketplace.json 为活数据（分类/策略/新增插件）；本快照只提供文案。
 *    中文表在 electron/codex-official-market.ts 的 OFFICIAL_PLUGIN_ZH（缺条目回落这里的英文）。
 */
export type OfficialPluginCatalogEntry = {
  slug: string; path: string; category: string; auth: string; apiCurated: boolean;
  displayName: string; description: string; version: string; license: string;
};

export const OFFICIAL_CATALOG_GENERATED_AT = "2026-10-03";

export const OFFICIAL_PLUGIN_CATALOG: Record<string, OfficialPluginCatalogEntry> = {
  "linear": { slug: "linear", path: "plugins/linear", category: "Productivity", auth: "ON_INSTALL", apiCurated: true, displayName: "Linear", description: "Search, create and update Linear issues, projects, and initiatives.", version: "5.0.1", license: "MIT" },
  "outlook-calendar": { slug: "outlook-calendar", path: "plugins/outlook-calendar", category: "Productivity", auth: "ON_INSTALL", apiCurated: false, displayName: "Outlook Calendar", description: "Connect Microsoft Outlook Calendar for scheduling, daily briefs, event prep, and safe meeting changes.", version: "0.1.8", license: "MIT" },
  "atlassian-rovo": { slug: "atlassian-rovo", path: "plugins/atlassian-rovo", category: "Productivity", auth: "ON_INSTALL", apiCurated: true, displayName: "Atlassian Rovo", description: "Manage Jira and Confluence fast", version: "1.0.6", license: "MIT" },
  "slack": { slug: "slack", path: "plugins/slack", category: "Communication", auth: "ON_INSTALL", apiCurated: true, displayName: "Slack", description: "Work with Slack using the configured Slack integration.", version: "0.1.7", license: "MIT" },
  "gmail": { slug: "gmail", path: "plugins/gmail", category: "Communication", auth: "ON_INSTALL", apiCurated: false, displayName: "Gmail", description: "Work with Gmail using the configured Gmail app connector.", version: "0.1.9", license: "MIT" },
  "google-calendar": { slug: "google-calendar", path: "plugins/google-calendar", category: "Productivity", auth: "ON_INSTALL", apiCurated: false, displayName: "Google Calendar", description: "Connect Google Calendar for scheduling, availability, daily briefs, and event management.", version: "1.2.6", license: "MIT" },
  "sharepoint": { slug: "sharepoint", path: "plugins/sharepoint", category: "Productivity", auth: "ON_INSTALL", apiCurated: false, displayName: "SharePoint", description: "Work with SharePoint using the configured Microsoft SharePoint app connector.", version: "0.1.7", license: "MIT" },
  "teams": { slug: "teams", path: "plugins/teams", category: "Communication", auth: "ON_INSTALL", apiCurated: false, displayName: "Teams", description: "Work with Teams using the configured Microsoft Teams app connector.", version: "0.1.8", license: "MIT" },
  "outlook-email": { slug: "outlook-email", path: "plugins/outlook-email", category: "Communication", auth: "ON_INSTALL", apiCurated: false, displayName: "Outlook Email", description: "Work with Outlook Email using the configured Microsoft Outlook app connector.", version: "0.1.7", license: "MIT" },
  "figma": { slug: "figma", path: "plugins/figma", category: "Creativity", auth: "ON_INSTALL", apiCurated: true, displayName: "Figma", description: "Figma workflows for design implementation, Code Connect templates, and design system rule generation.", version: "2.0.20", license: "LicenseRef-Figma-Developer-Terms" },
  "game-studio": { slug: "game-studio", path: "plugins/game-studio", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Game Studio", description: "Design, prototype, and ship browser games with guided 2D and 3D workflows, asset pipelines, and playtesting support.", version: "0.1.2", license: "MIT" },
  "stripe": { slug: "stripe", path: "plugins/stripe", category: "Finance", auth: "ON_INSTALL", apiCurated: true, displayName: "Stripe", description: "Develop your payments integration faster with the ability to create products, prices, and payment links directly in ChatGPT.", version: "7.0.0", license: "" },
  "superpowers": { slug: "superpowers", path: "plugins/superpowers", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Superpowers", description: "An agentic skills framework & software development methodology that works: planning, TDD, debugging, and collaboration workflows.", version: "6.3.0", license: "MIT" },
  "vercel": { slug: "vercel", path: "plugins/vercel", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Vercel", description: "Build and deploy web apps and agents", version: "0.21.4", license: "Apache-2.0" },
  "github": { slug: "github", path: "plugins/github", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "GitHub", description: "Inspect repositories, triage pull requests and issues, debug CI, and publish changes through a hybrid GitHub connector and CLI workflow.", version: "0.1.12", license: "MIT" },
  "circleci": { slug: "circleci", path: "plugins/circleci", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "CircleCI", description: "Build, test, and deploy any application", version: "1.0.4", license: "MIT" },
  "canva": { slug: "canva", path: "plugins/canva", category: "Creativity", auth: "ON_INSTALL", apiCurated: true, displayName: "Canva", description: "Bring your Canva design workflow into Codex and create, refine, and review designs through natural conversation.", version: "14.0.0", license: "" },
  "google-drive": { slug: "google-drive", path: "plugins/google-drive", category: "Productivity", auth: "ON_INSTALL", apiCurated: false, displayName: "Google Drive", description: "Use Google Drive as the single entrypoint for Drive, Docs, Sheets, and Slides work.", version: "0.1.15", license: "MIT" },
  "cloudflare": { slug: "cloudflare", path: "plugins/cloudflare", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Cloudflare", description: "Cloudflare platform plugin with curated skills for Workers, Wrangler, and Agents SDK plus the official Cloudflare API MCP server.", version: "0.1.2", license: "MIT" },
  "sentry": { slug: "sentry", path: "plugins/sentry", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Sentry", description: "Inspect recent issues and events in Sentry from Codex.", version: "0.1.2", license: "MIT" },
  "notion": { slug: "notion", path: "plugins/notion", category: "Productivity", auth: "ON_INSTALL", apiCurated: true, displayName: "Notion", description: "Notion workflows for implementation planning, research synthesis, meeting preparation, and knowledge capture.", version: "0.1.7", license: "MIT" },
  "build-web-apps": { slug: "build-web-apps", path: "plugins/build-web-apps", category: "Developer Tools", auth: "ON_USE", apiCurated: true, displayName: "Build Web Apps", description: "Build web apps with frontend asset design, browser testing, UI components, payments, and database guidance.", version: "0.1.2", license: "MIT" },
  "build-macos-apps": { slug: "build-macos-apps", path: "plugins/build-macos-apps", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Build macOS Apps", description: "Build, run, test, debug, instrument, and implement local macOS apps using Xcode, SwiftUI, AppKit interop, unified logging, and shell-first desktop workflows.", version: "0.1.4", license: "MIT" },
  "build-ios-apps": { slug: "build-ios-apps", path: "plugins/build-ios-apps", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Build iOS Apps", description: "Build iOS apps with workflows for App Intents, SwiftUI UI work, Simulator mirroring in the Codex in-app browser, performance profiling, leak investigation, and simulator debugging.", version: "0.1.2", license: "MIT" },
  "build-web-data-visualization": { slug: "build-web-data-visualization", path: "plugins/build-web-data-visualization", category: "Developer Tools", auth: "ON_USE", apiCurated: true, displayName: "Build Web Data Visualization", description: "Design, critique, implement, test, and export web data visualizations in Codex, including charts, maps, dashboards, Gantt, UML, scrollytelling, reports, slides, mobile views, shar…", version: "0.1.21", license: "MIT" },
  "test-android-apps": { slug: "test-android-apps", path: "plugins/test-android-apps", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Test Android Apps", description: "Test Android apps with emulator workflows for reproduction, screenshots, UI inspection, log capture, and performance profiling.", version: "0.1.2", license: "MIT" },
  "life-science-research": { slug: "life-science-research", path: "plugins/life-science-research", category: "Education & Research", auth: "ON_INSTALL", apiCurated: true, displayName: "Life Science Research", description: "General life-sciences research workflows with query routing, evidence synthesis, and optional parallel subagent analysis across genetics, omics, biology, chemistry, structure, cli…", version: "1.0.3", license: "Proprietary" },
  "zotero": { slug: "zotero", path: "plugins/zotero", category: "Education & Research", auth: "ON_INSTALL", apiCurated: true, displayName: "Zotero", description: "Work with Zotero from Codex: search your library, export BibTeX, insert citations, and import references through the Zotero desktop app.", version: "0.1.2", license: "MIT" },
  "expo": { slug: "expo", path: "plugins/expo", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Expo", description: "Official Expo skills for building, deploying, upgrading, and debugging Expo and React Native apps.", version: "1.0.2", license: "MIT" },
  "coderabbit": { slug: "coderabbit", path: "plugins/coderabbit", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "CodeRabbit", description: "AI-powered code review in Codex, powered by CodeRabbit.", version: "1.1.4", license: "MIT" },
  "remotion": { slug: "remotion", path: "plugins/remotion", category: "Creativity", auth: "ON_INSTALL", apiCurated: true, displayName: "Remotion", description: "Remotion video creation skills — best practices, animations, audio, captions, 3D, and more for building programmatic videos with React.", version: "1.0.7", license: "MIT" },
  "plugin-eval": { slug: "plugin-eval", path: "plugins/plugin-eval", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Plugin Eval", description: "Evaluate Codex skills and plugins from chat with a beginner-friendly start command, local-first reports, token budget explanations, and guided benchmarking.", version: "0.1.2", license: "MIT" },
  "granola": { slug: "granola", path: "plugins/granola", category: "Productivity", auth: "ON_INSTALL", apiCurated: true, displayName: "Granola", description: "Granola MCP connects your meeting history to ChatGPT so your assistant can pull real context from past conversations while you work.", version: "1.0.0", license: "MIT" },
  "temporal": { slug: "temporal", path: "plugins/temporal", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Temporal", description: "Comprehensive skill for the entire Temporal lifecycle — developing applications, using the Temporal CLI, running and managing Temporal Server, and working with Temporal Cloud.", version: "0.4.0", license: "MIT" },
  "monday-com": { slug: "monday-com", path: "plugins/monday-com", category: "Productivity", auth: "ON_INSTALL", apiCurated: true, displayName: "monday.com", description: "The monday.com AI Connector brings core platform capabilities directly to agents and AI assistants.", version: "2.0.0", license: "" },
  "hyperframes": { slug: "hyperframes", path: "plugins/hyperframes", category: "Creativity", auth: "ON_INSTALL", apiCurated: true, displayName: "HyperFrames by HeyGen", description: "Write HTML, render video.", version: "0.1.2", license: "Apache-2.0" },
  "supabase": { slug: "supabase", path: "plugins/supabase", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Supabase", description: "Manage Supabase projects directly through ChatGPT.", version: "1.0.0", license: "MIT" },
  "codex-security": { slug: "codex-security", path: "plugins/codex-security", category: "Security", auth: "ON_USE", apiCurated: true, displayName: "Codex Security", description: "Codex Security workflows for security scans, analysis, and investigation.", version: "0.1.24", license: "Proprietary" },
  "twilio-developer-kit": { slug: "twilio-developer-kit", path: "plugins/twilio-developer-kit", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Twilio Developer Kit", description: "Twilio Skills provide procedural knowledge for AI coding agents — which APIs to use, in what order, and what to avoid.", version: "0.2.2", license: "MIT" },
  "openai-developers": { slug: "openai-developers", path: "plugins/openai-developers", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "OpenAI Developers", description: "Build with OpenAI APIs, Agents SDK, and ChatGPT Apps, and create and save OpenAI API keys from Codex.", version: "1.2.3", license: "Proprietary" },
  "datadog": { slug: "datadog", path: "plugins/datadog", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Datadog (Preview)", description: "Available for US1 customers only.", version: "10.0.0", license: "" },
  "mixpanel-headless": { slug: "mixpanel-headless", path: "plugins/mixpanel-headless", category: "Data & Analytics", auth: "ON_INSTALL", apiCurated: true, displayName: "Mixpanel Headless", description: "Analyze Mixpanel data with the mixpanel_headless Python SDK and Codex skills.", version: "0.1.2", license: "MIT" },
  "zoom": { slug: "zoom", path: "plugins/zoom", category: "Communication", auth: "ON_INSTALL", apiCurated: false, displayName: "Zoom", description: "Smart meeting insights from Zoom", version: "1.0.0", license: "MIT" },
  "ngs-analysis": { slug: "ngs-analysis", path: "plugins/ngs-analysis", category: "Education & Research", auth: "ON_INSTALL", apiCurated: true, displayName: "Life Sciences NGS Analysis", description: "Guided NGS intake, local execution, and public-pipeline routing for BCL, FASTQ, DNA variant, RNA-seq, single-cell, epigenomics, amplicon, and metagenomics analyses, with deeper de…", version: "1.0.3", license: "MIT" },
  "nvidia": { slug: "nvidia", path: "plugins/nvidia", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "NVIDIA", description: "Skills for NVIDIAs ecosystem spans GPU acceleration, CUDA, AI agents, inference, robotics, Physical AI, Omniverse, and simulation.", version: "1.0.4", license: "Apache-2.0 AND CC-BY-4.0" },
  "magicpath": { slug: "magicpath", path: "plugins/magicpath", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "MagicPath", description: "Use MagicPath to find, inspect, install, create, and edit UI components from Codex.", version: "0.1.2", license: "UNLICENSED" },
  "openai-ads-conversions": { slug: "openai-ads-conversions", path: "plugins/openai-ads-conversions", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "OpenAI Ads Conversions", description: "Set up OpenAI Ads Measurement Pixel and optional Conversions API instrumentation.", version: "0.1.2", license: "Proprietary" },
  "boltz-api-cli": { slug: "boltz-api-cli", path: "plugins/boltz-api-cli", category: "Scientific Research", auth: "ON_INSTALL", apiCurated: true, displayName: "Boltz", description: "Predict structures, screen molecules and proteins, and design binders.", version: "0.1.1", license: "MIT" },
  "posthog": { slug: "posthog", path: "plugins/posthog", category: "Data & Analytics", auth: "ON_INSTALL", apiCurated: true, displayName: "PostHog", description: "PostHog gives your AI agent direct access to your product analytics, feature flags, experiments, error tracking, surveys, logs, and LLM analytics.", version: "1.0.0", license: "MIT" },
  "shopify": { slug: "shopify", path: "plugins/shopify", category: "Business & Operations", auth: "ON_INSTALL", apiCurated: false, displayName: "Shopify", description: "Shopify for ChatGPT makes store building and management as easy as having a conversation.", version: "3.0.0", license: "" },
  "product-design": { slug: "product-design", path: "plugins/product-design", category: "Creativity", auth: "ON_USE", apiCurated: true, displayName: "Product Design", description: "The Product Design plugin is built for turning early ideas into prototypes teams can review.", version: "0.1.52", license: "Proprietary" },
  "data-analytics": { slug: "data-analytics", path: "plugins/data-analytics", category: "Data & Analytics", auth: "ON_USE", apiCurated: false, displayName: "Data Analytics", description: "Answer product and business questions with data", version: "0.2.8", license: "Proprietary" },
  "dropbox": { slug: "dropbox", path: "plugins/dropbox", category: "Productivity", auth: "ON_INSTALL", apiCurated: true, displayName: "Dropbox", description: "The Dropbox plugin for ChatGPT connects your Dropbox files directly to ChatGPT.", version: "5.0.1", license: "" },
  "creative-production": { slug: "creative-production", path: "plugins/creative-production", category: "Creativity", auth: "ON_USE", apiCurated: false, displayName: "Creative Production", description: "Explore campaign ideas, concept images, mood boards, product placements, ad directions, listing images, social posts, and launch assets.", version: "0.1.25", license: "Proprietary" },
  "airtable": { slug: "airtable", path: "plugins/airtable", category: "Productivity", auth: "ON_INSTALL", apiCurated: false, displayName: "Airtable", description: "Bring operational data and context into the flow of your ChatGPT conversations.", version: "6.0.1", license: "" },
  "crowdstrike-falcon-foundry": { slug: "crowdstrike-falcon-foundry", path: "", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "CrowdStrike Falcon Foundry", description: "", version: "", license: "" },
  "crowdstrike-falcon-fusion": { slug: "crowdstrike-falcon-fusion", path: "", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "CrowdStrike Falcon Fusion", description: "", version: "", license: "" },
  "adobe": { slug: "adobe", path: "plugins/adobe", category: "Creativity", auth: "ON_INSTALL", apiCurated: false, displayName: "Adobe", description: "Adobe unlocks more ways to create and get work done from the conversation.", version: "8.0.0", license: "" },
  "public-equity-investing": { slug: "public-equity-investing", path: "plugins/public-equity-investing", category: "Finance", auth: "ON_USE", apiCurated: false, displayName: "Public Equity Investing", description: "Public equity investing workflows for listed-company research, earnings analysis, valuation, model updates, long/short pitches, catalysts, thesis tracking, ETF/index and constitue…", version: "0.1.31", license: "Proprietary" },
  "clickup": { slug: "clickup", path: "plugins/clickup", category: "Productivity", auth: "ON_INSTALL", apiCurated: true, displayName: "ClickUp", description: "Turn Codex into your ClickUp command center.", version: "1.0.3", license: "MIT" },
  "lovable": { slug: "lovable", path: "plugins/lovable", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: false, displayName: "Lovable", description: "Build apps and websites", version: "2.0.1", license: "" },
  "consensus": { slug: "consensus", path: "plugins/consensus", category: "Education & Research", auth: "ON_INSTALL", apiCurated: true, displayName: "Consensus", description: "Consensus is the go-to MCP for academic research.", version: "4.0.0", license: "" },
  "chatcut": { slug: "chatcut", path: "plugins/chatcut", category: "Creativity", auth: "ON_INSTALL", apiCurated: true, displayName: "ChatCut", description: "Install, open, and connect the signed ChatCut Desktop app from Codex.", version: "1.0.4", license: "GPL-3.0-only" },
  "higgsfield": { slug: "higgsfield", path: "plugins/higgsfield", category: "Creativity", auth: "ON_INSTALL", apiCurated: true, displayName: "Higgsfield", description: "Generate images and videos from a text prompt or your own photo.", version: "1.2.1", license: "" },
  "qodo": { slug: "qodo", path: "codex-packages/qodo", category: "Developer Tools", auth: "ON_INSTALL", apiCurated: true, displayName: "Qodo", description: "", version: "", license: "" },
};
