/**
 * IPC 域注册表（架构改造批 4 前置：channel → 所属模块的「接口在哪」查表）。
 *
 * 记账规则：
 *   · status=in-main    → handler 体仍在 electron/main.ts（待拆，账本 count 应 = main.ts 实际数）
 *   · status=in-features → 已拆到 electron/features/<file>（搬走 = 该域通道必须从 main.ts 消失）
 *   · status=shell      → 壳族基础设施（window/dialog/clipboard/fs/theme/notify/external/shell/awake/updates），留在 main 顶层不拆
 *                         （09-22：app 族 8 个通道已整体拆到 features/app-diagnostics.ts，从 shell 族移出）
 *   · count            → 该域 handler 总数（拆分前基线，搬走后不回填 0，账本永远记总量）
 *   · channels         → 已拆域的完整通道清单，供预检守卫【90】校验「搬干净没有」
 *
 * 每拆一个域：把 handler 体搬进 electron/features/<域>.ts 后，改这里 status=in-features、
 * file=features/<域>.ts、channels 填全 —— 预检【90】会盯着 main.ts 里该域通道数必须归零。
 */
export type IpcDomainStatus = "in-main" | "in-features" | "shell";

export interface IpcDomainEntry {
  /** 域前缀（channel 冒号前部分，如 relay / voice） */
  prefix: string;
  /** 该域 handler 总数（拆分前基线） */
  count: number;
  /** 现在在哪：in-main / in-features / shell */
  status: IpcDomainStatus;
  /** 所在文件：in-main|shell → "main.ts"；in-features → "features/<file>.ts" */
  file: string;
  /** 已拆域的完整通道清单（status=in-features 时必填） */
  channels?: string[];
  /** 备注（计划落点 / 拆分注意） */
  note?: string;
}

export const IPC_DOMAINS: IpcDomainEntry[] = [
  { prefix: "pet", count: 10, status: "in-features", file: "features/pet-ipc.ts",
    channels: ["pet:list", "pet:settings-get", "pet:settings-set", "pet:state", "pet:roots", "pet:open-dir", "pet:import", "pet:toggle", "pet:show", "pet:hide"],
    note: "09-30 新增：桌面宠物（官方 Codex 宠物格式的发现/校验/设置）。宠物本体渲染在独立透明置顶浮窗（features/pet-window.ts，**不登记 window-bus**）；图集经**窄口径 `pet://` 协议**读取（只放行宠物目录 + 图片扩展名；不放宽 harness-image 的可信根）；状态归约在 features/pet-state.ts（引擎事件 → 官方九态）",
  },
  { prefix: "drama-canvas", count: 7, status: "in-features", file: "features/drama-canvas.ts",
    channels: ["drama-canvas:asset-write", "drama-canvas:storyboard-file-remove", "drama-canvas:polish-prompt", "drama-canvas:describe-image", "drama-canvas:output-dir", "drama-canvas:output-dir-set", "drama-canvas:board-sync"],
    note: "09-27 新增：AI 短剧无限画布。画布/分镜表本体走 localStorage + fs:write（文本即可），这条专管**二进制素材**（本地 TTS 合成的配音 WAV）；09-29 加 polish-prompt（「AI 润色」，主进程用已配置模型发一次短请求，不开会话）与 describe-image（「锁主体」：视觉模型把商品图反推成固定主体描述，六类图共用）与 board-sync（画布快照镜像：渲染层防抖推 {name,flow,nodes,edges} 存 userData/drama-canvas/boards.json，workflow_read 工具的数据源）",
  },
  { prefix: "laya", count: 4, status: "in-features", file: "features/laya-service.ts",
    channels: ["laya:status", "laya:install", "laya:uninstall", "laya:decide-effort"],
    note: "10-01 新增：Laya 智能判断（GitHub NandhaKishorM/laya，Apache-2.0，非自回归决策引擎 33ms）。laya-serve HTTP 服务（127.0.0.1 + API key + 闲置 10 分钟退出）由 features/laya-service.ts 管道管理；权重走 hf-mirror。首个消费方 = 思考等级自动切换（渲染层「自动」档）。" },
  { prefix: "phone", count: 7, status: "in-features", file: "features/phone-harness-ipc.ts",
    channels: ["phone:harness:status", "phone:harness:install", "phone:harness:uninstall", "phone:harness:doctor", "phone:harness:guides", "phone:harness:open-settings", "phone:harness:wire-adb"],
    note: "09-27 新增：手机控制（phone-harness）。不是 MCP 服务 ⇒ 走「pip 包 + 技能注册」，装完强制关上游遥测；iPhone 通道仅 darwin",
  },
  { prefix: "team-runs", count: 1, status: "in-features", file: "features/team-runs-ipc.ts",
    channels: ["team-runs:list"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "team-threads", count: 2, status: "in-features", file: "features/team-threads-ipc.ts",
    channels: ["team-threads:map", "team-threads:team-of"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "thread-runtime", count: 6, status: "in-features", file: "features/thread-runtime-ipc.ts",
    channels: ["thread-runtime:dispatch-owner", "thread-runtime:get", "thread-runtime:list", "thread-runtime:patch", "thread-runtime:release-dispatch", "thread-runtime:seed"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "agents", count: 11, status: "in-features", file: "features/agents-ipc.ts",
    channels: ["agents:archive", "agents:catalog", "agents:delegated", "agents:delegated-of", "agents:dispatch-call", "agents:enabled-notice", "agents:invoke", "agents:notice", "agents:off-notice", "agents:thread-role", "agents:tool-description"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用；10-05 加 agents:dispatch-call（能力网关：内置 MCP 工具面在引擎 0.157 后对模型不可见，用 harness_tools 接回来，执行端复用 dispatchRpcCall）",
  },
  { prefix: "theme", count: 1, status: "shell", file: "main.ts",
    channels: ["theme:apply"],
  },
  { prefix: "bot-binding", count: 2, status: "in-features", file: "features/bot-binding-ipc.ts",
    channels: ["bot-binding:get", "bot-binding:set"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "bots", count: 2, status: "in-features", file: "features/bots-ipc.ts",
    channels: ["bots:get", "bots:set"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "bot-stream", count: 2, status: "in-features", file: "features/bot-stream-ipc.ts",
    channels: ["bot-stream:get", "bot-stream:set"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
    { prefix: "video", count: 7, status: "in-features", file: "features/video-gen.ts",
    channels: ["video:providers", "video:config-read", "video:config-save", "video:submit", "video:poll", "video:download", "video:concat"],
    note: "09-27 内置视频生成接口（国内外 8 家）；凭证存 userData/video-providers.json",
  },
  { prefix: "queue-timer", count: 2, status: "in-features", file: "features/queue-timer-ipc.ts",
    channels: ["queue-timer:set", "queue-timer:cancel"],
    note: "09-28 排队消息定时发送：主进程定时器到点广播 queue-timer:due，启动动作在渲染层",
  },
{ prefix: "weixin", count: 6, status: "in-features", file: "features/weixin-ipc.ts",
    channels: ["weixin:cancel-login", "weixin:logout", "weixin:poll-login", "weixin:send", "weixin:start-login", "weixin:status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "telegram", count: 3, status: "in-features", file: "features/telegram-ipc.ts",
    channels: ["telegram:connect", "telegram:logout", "telegram:status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "channels", count: 1, status: "in-features", file: "features/channels-ipc.ts",
    channels: ["channels:status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "feishu", count: 5, status: "in-features", file: "features/feishu-ipc.ts",
    channels: ["feishu:connect", "feishu:logout", "feishu:qr-cancel", "feishu:qr-start", "feishu:qr-status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "dingtalk", count: 2, status: "in-features", file: "features/dingtalk-ipc.ts",
    channels: ["dingtalk:connect", "dingtalk:logout"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "qq", count: 5, status: "in-features", file: "features/qq-ipc.ts",
    channels: ["qq:connect", "qq:logout", "qq:qr-cancel", "qq:qr-start", "qq:qr-status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "wecom-webhook", count: 3, status: "in-features", file: "features/wecom-webhook-ipc.ts",
    channels: ["wecom-webhook:connect", "wecom-webhook:logout", "wecom-webhook:test"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "ponytail", count: 2, status: "in-features", file: "features/ponytail-ipc.ts",
    channels: ["ponytail:mode:get", "ponytail:mode:set"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "codex", count: 3, status: "in-features", file: "features/codex-ipc.ts",
    channels: ["codex:request", "codex:respond", "codex:set-active-thread"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "user", count: 1, status: "in-features", file: "features/user-ipc.ts",
    channels: ["user:name"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "app", count: 8, status: "in-features", file: "features/app-diagnostics.ts",
    channels: ["app:doctor", "app:engine-info", "app:home-dir", "app:perf-counters", "app:relaunch", "app:storage-clear", "app:storage-info", "app:userData"],
    note: "09-22 拆出：这 8 个通道全是「应用信息 / 环境自检 / 存储管理 / 重启」语义（不是壳族基础设施），整体搬进 features/app-diagnostics.ts 后从 shell 族移出",
  },
  { prefix: "work-logs", count: 3, status: "in-features", file: "features/work-logs.ts",
    channels: ["work-logs:scan", "work-logs:read", "work-logs:delete"],
    note: "09-30 新增：各项目的**工作日志与项目记忆**管理（<项目>/.codex-harness/memory/**：长期记忆 / 坑与纪律 / 每日日志 / 归档 / 项目资料）—— 设置 → 数据管理 → 工作日志。⛔ 与会话本身（归档 / 删除，在「归档管理」页）不是一回事；删除销毁性",
  },
  { prefix: "capabilities", count: 1, status: "in-features", file: "features/capabilities-ipc.ts",
    channels: ["capabilities:snapshot"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用；10-03 从 user-ipc 按前缀拆出为独立板块（一个板块恒等于一个域前缀）",
  },
  { prefix: "window", count: 4, status: "shell", file: "main.ts",
    channels: ["window:popout-thread", "window:popout-close", "window:popout-id", "window:popout-list"],
    note: "09-24 从 preload 手写区迁进 manifest（登记面补全，守卫【2】按 channel 字面判登记）",
  },
  { prefix: "engine", count: 4, status: "in-features", file: "features/engine-ipc.ts",
    channels: ["engine:active-turns", "engine:check-update", "engine:perform-update", "engine:restart-log"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "builtin", count: 5, status: "in-features", file: "features/builtin-ipc.ts",
    channels: ["builtin:describe-image", "builtin:generate-image", "builtin:probe", "builtin:read", "builtin:save"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "relay", count: 14, status: "in-features", file: "features/relay-ipc.ts",
    channels: ["relay:login", "relay:load-account", "relay:accounts", "relay:toggle-account", "relay:switch-account", "relay:remove-account", "relay:overview", "relay:create-key", "relay:select", "relay:key-billing", "relay:register", "relay:payment-plans", "relay:open-purchase", "relay:keys-all"],
    note: "09-21 拆出：跨域符号经 RelayIpcDeps 注入（模型域 4 个 + describeNetworkError + server 单例）；main.ts 的「启用/停用供应商」联动用导出的 readRelayStore/writeRelayStore 薄包装",
  },
  { prefix: "openai", count: 12, status: "in-features", file: "features/openai-ipc.ts",
    channels: ["openai:account-remove", "openai:account-switch", "openai:accounts", "openai:capture-login", "openai:import-file", "openai:login-cancel", "openai:login-start", "openai:login-status", "openai:models", "openai:set-proxy", "openai:toggle-account", "openai:usage"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "prompt", count: 1, status: "in-features", file: "features/prompt-ipc.ts",
    channels: ["prompt:enhance"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "terminal", count: 5, status: "in-features", file: "features/terminal-ipc.ts",
    channels: ["terminal:input", "terminal:list", "terminal:ready", "terminal:resize", "terminal:restart"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "updates", count: 4, status: "in-features", file: "features/updates-ipc.ts",
    channels: ["updates:check", "updates:download", "updates:reveal", "updates:install"],
    note: "09-22 拆出：updates 全部 4 个更新链通道 + 权威状态 lastUpdateInfo / lastVerifiedUpdatePath",
  },
  { prefix: "plugin", count: 1, status: "in-features", file: "features/plugin-ipc.ts",
    channels: ["plugin:validate"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "remote", count: 11, status: "in-features", file: "features/remote-ipc.ts",
    channels: ["remote:approve", "remote:deny", "remote:devices", "remote:pair-rotate", "remote:pair-state", "remote:qrcode", "remote:revoke", "remote:send", "remote:start", "remote:status", "remote:stop"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "bot", count: 7, status: "in-features", file: "features/bot-ipc.ts",
    channels: ["bot:approve", "bot:bind-consume", "bot:bind-qrcode", "bot:bind-status", "bot:deny", "bot:pair-state", "bot:revoke"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "notify", count: 1, status: "in-features", file: "features/notify-ipc.ts",
    channels: ["notify:show"],
    note: "09-22 拆出：系统通知通道；10-03 从 shell-misc-ipc 按前缀拆出为独立板块",
  },
  { prefix: "awake", count: 1, status: "in-features", file: "features/awake-ipc.ts",
    channels: ["awake:set"],
    note: "09-22 拆出：防休眠通道（状态 awakeId 随迁）；10-03 从 shell-misc-ipc 按前缀拆出为独立板块，awakeId 归本域私有并在 ctx.effect 内停表",
  },
  { prefix: "tools", count: 1, status: "in-features", file: "features/tools-ipc.ts",
    channels: ["tools:status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "runtime", count: 4, status: "in-features", file: "features/runtime-ipc.ts",
    channels: ["runtime:health", "runtime:install", "runtime:list", "runtime:uninstall"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "browser", count: 3, status: "in-features", file: "features/browser-ipc.ts",
    channels: ["browser:cloak-status", "browser:open-cloak", "browser:popout"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "git", count: 1, status: "in-features", file: "features/git-ipc.ts",
    channels: ["git:diff"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "fs", count: 4, status: "in-features", file: "features/fs-ipc.ts",
    channels: ["fs:write", "fs:read", "fs:exists", "fs:reveal"],
    note: "09-22 拆出：fs 全部 3 个文件读写通道；isInsideTrustedRoots 经 ../main 活绑定且在 handler 内求值",
  },
  { prefix: "model-viewer", count: 1, status: "in-features", file: "features/model-viewer-ipc.ts",
    channels: ["model-viewer:read"],
    note: "10-05 新增：3D 模型预览的读通道（GLB/glTF 字节，Uint8Array 结构化克隆直传）；路径闸 = resolveModelPath（可信根 + 扩展名白名单 + 256MB 上限），与网关 preview_3d 推送的 model-viewer:open（渲染层手写桥，不在 manifest）共用",
  },
  { prefix: "dialog", count: 6, status: "in-features", file: "features/dialog-ipc.ts",
    channels: ["dialog:directory", "dialog:directory-at", "dialog:images", "dialog:files", "dialog:ssh-key", "dialog:save-as"],
    note: "09-22 拆出：dialog 文件对话框通道；mainWindow/trustPicked/isInsideTrustedRoots 经 main 导出的活绑定取用；09-26 增 dialog:save-as（文件卡片右键另存为，源限可信根）",
  },
  { prefix: "dataDir", count: 2, status: "in-features", file: "features/data-dir-ipc.ts",
    channels: ["dataDir:read", "dataDir:prepare"],
    note: "09-25 新增：自定义数据目录（指路牌=默认目录下 data-dir.json；迁移在下次启动引擎 spawn 前由 data-dir.ts 执行；重启复用 app:relaunch）",
  },
  { prefix: "skills", count: 12, status: "in-features", file: "features/skills-ipc.ts",
    channels: ["skills:import", "skills:local-list", "skills:local-remove", "skills:market-install", "skills:market-install-light", "skills:market-list", "skills:set-enabled", "skills:set-enabled-batch", "skills:pool-describe", "skills:pool-set", "skills:builtin-switch-get", "skills:builtin-switch-set"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用；09-27 加共享技能池（skill-pool.ts）",
  },
  { prefix: "skill-discipline", count: 1, status: "in-features", file: "features/skill-discipline-ipc.ts",
    channels: ["skill-discipline:get"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "plugins", count: 6, status: "in-features", file: "features/plugins-ipc.ts",
    channels: ["plugins:market-install", "plugins:market-installed", "plugins:market-list", "plugins:market-uninstall", "plugins:set-enabled", "plugins:set-linked-enabled"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "codex-official-market", count: 5, status: "in-features", file: "features/codex-official-market-ipc.ts",
    channels: ["codex-official-market:categories", "codex-official-market:install", "codex-official-market:installed", "codex-official-market:list", "codex-official-market:uninstall"],
    note: "10-03 新增：Codex 官方插件市场（GitHub openai/plugins 国内镜像）——与 plugins（Gitee 镜像源）是两个源、两个板块",
  },
  { prefix: "hooks", count: 2, status: "in-features", file: "features/hooks-ipc.ts",
    channels: ["hooks:set-enabled", "hooks:trust"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "connectors", count: 7, status: "in-features", file: "features/connectors-ipc.ts",
    channels: ["connectors:list", "connectors:oauth-cancel", "connectors:oauth-start", "connectors:remove", "connectors:save", "connectors:set-enabled", "connectors:templates"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "mcp-servers", count: 4, status: "in-features", file: "features/mcp-servers-ipc.ts",
    channels: ["mcp-servers:overrides", "mcp-servers:permissions", "mcp-servers:set-enabled", "mcp-servers:set-tool-permission"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "personalization", count: 6, status: "in-features", file: "features/personalization-ipc.ts",
    channels: ["personalization:mark-greeted", "personalization:read", "personalization:save", "personalization:save-identity", "personalization:setNickname", "personalization:verify"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "appSettings", count: 2, status: "in-features", file: "features/app-settings-ipc.ts",
    channels: ["appSettings:read", "appSettings:save"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "model-specs", count: 1, status: "in-features", file: "features/model-specs-ipc.ts",
    channels: ["model-specs:read"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "ssh", count: 12, status: "in-features", file: "features/ssh-ipc.ts",
    channels: ["ssh:delete", "ssh:exec", "ssh:export", "ssh:import", "ssh:list", "ssh:save", "ssh:session-close", "ssh:session-open", "ssh:session-resize", "ssh:session-write", "ssh:set-enabled", "ssh:test"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "threads", count: 5, status: "in-features", file: "features/threads-ipc.ts",
    channels: ["threads:export", "threads:export-markdown", "threads:import", "threads:import-conversation", "threads:preview-conversation"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "commands", count: 5, status: "in-features", file: "features/commands-ipc.ts",
    channels: ["commands:delete", "commands:expand", "commands:list", "commands:read", "commands:save"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "subagents", count: 3, status: "in-features", file: "features/subagents-ipc.ts",
    channels: ["subagents:list", "subagents:remove", "subagents:save"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用；10-04 删 subagents:invoke（绕过调度闸门与 delegateRegistry 登记的旁路，用户拍板合并成单一工具 agent_invoke）",
  },
  { prefix: "teams", count: 9, status: "in-features", file: "features/teams-ipc.ts",
    channels: ["teams:invoke-member", "teams:list", "teams:member-session", "teams:remove", "teams:reset-defaults", "teams:save", "teams:session-config", "teams:start-session", "teams:tools"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "clipboard", count: 4, status: "in-features", file: "features/clipboard-ipc.ts",
    channels: ["clipboard:image", "clipboard:write", "clipboard:write-image", "clipboard:read-files"],
    note: "09-22 拆出：clipboard 全部 4 个剪贴板通道；imagesDir 改为 handler 内惰性求值（app.getPath 不落模块顶层）",
  },
  { prefix: "expert-market", count: 2, status: "in-features", file: "features/expert-market-ipc.ts",
    channels: ["expert-market:install", "expert-market:list"],
    note: "10-01 新增：SkillHub 专家市场包（skillhub.cn/skillspackage，55 包）。装包 = 元技能落盘 + orchestration.children 子技能逐个装 + 专家中心新增对应专家卡片（readExpertTeams/writeExpertTeams）",
  },
  { prefix: "kb", count: 9, status: "in-features", file: "features/knowledge-base-ipc.ts",
    channels: ["kb:add-files", "kb:add-text", "kb:embed-install", "kb:embed-status", "kb:embed-uninstall", "kb:list", "kb:read", "kb:remove", "kb:search"],
    note: "10-01 新增：项目级本地知识库（<项目>/.codex-harness/knowledge/）。导入 md/txt 文档、分块全文检索（v1 零依赖）、删除；10-04 加 embed-* 三通道：本地语义后端（transformers.js + bge-small-zh）按需下载（npm 树 463MB 不随包），知识库页内装/卸/查状态，进度走 runtime:progress(id=kb-embedding)",
    },
  { prefix: "whatsnew", count: 3, status: "in-features", file: "features/whats-new-ipc.ts",
    channels: ["whatsnew:ack", "whatsnew:history", "whatsnew:state"],
    note: "10-06 新增：「更新后首次启动」的新功能介绍弹窗。该不该弹 / 弹什么**全在主进程判定**（要点数据 electron/whats-new-notes.ts，看过记录 userData/whats-new.json）；ack 只接受当前版本号（权威值在主进程，渲染层传别的值一律拒）；10-07 加 history（全量版本要点，新手引导→版本更新日志用；同一份数据源，Release 链接在主进程拼）",
  },
  { prefix: "soul-market", count: 4, status: "in-features", file: "features/soul-market-ipc.ts",
    channels: ["soul-market:apply", "soul-market:current", "soul-market:get", "soul-market:list"],
    note: "10-01 新增：SkillHub 人格市场（skillhub.cn/soul，16 套）。应用 = 写 personalization.persona + 同步 $CODEX_HOME/AGENTS.md（引擎每会话重读，新会话即生效）；soul-market:apply slug=null 还原默认",
  },
  { prefix: "pasted-text", count: 3, status: "in-features", file: "features/pasted-text-ipc.ts",
    channels: ["pasted-text:read", "pasted-text:save", "pasted-text:update"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "external", count: 1, status: "in-features", file: "features/external-ipc.ts",
    channels: ["external:open"],
    note: "09-22 拆出：外链打开（filePreviewAllowed 活绑定）；10-03 从 shell-misc-ipc 按前缀拆出为独立板块",
  },
  { prefix: "shell", count: 1, status: "in-features", file: "features/shell-ipc.ts",
    channels: ["shell:reveal"],
    note: "09-22 拆出：定位文件（isInsideOrEqualTrustedRoots 活绑定）；10-03 从 shell-misc-ipc 按前缀拆出为独立板块",
  },
  { prefix: "scratch", count: 1, status: "in-features", file: "features/scratch-ipc.ts",
    channels: ["scratch:create"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "custom-model", count: 12, status: "in-features", file: "features/custom-model-ipc.ts",
    channels: ["custom-model:apply", "custom-model:list", "custom-model:probe", "custom-model:read", "custom-model:remove", "custom-model:remove-model", "custom-model:save", "custom-model:select", "custom-model:set-effort", "custom-model:set-enabled", "custom-model:set-model", "custom-model:upsert-model"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "bridge", count: 1, status: "in-features", file: "features/bridge-ipc.ts",
    channels: ["bridge:status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "channel-bot", count: 3, status: "in-features", file: "features/channel-bot-ipc.ts",
    channels: ["channel-bot:read", "channel-bot:save", "channel-bot:test"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "memory", count: 29, status: "in-features", file: "features/memory-ipc.ts",
    channels: [ "memory:backend:read", "memory:backend:set", "memory:delete", "memory:distill", "memory:fabric-entries", "memory:fabric-namespaces", "memory:fabric-write", "memory:gateway:read", "memory:gateway:save", "memory:gateway:test", "memory:hygiene:apply", "memory:hygiene:plan", "memory:layers:context", "memory:layers:read", "memory:layers:write", "memory:list", "memory:mcp:install", "memory:mcp:uninstall", "memory:mcp:verify", "memory:mode-read", "memory:mode-set", "memory:recall", "memory:reset", "memory:role-context", "memory:role-sessions", "memory:save", "memory:search", "memory:workspace-enabled:read", "memory:workspace-enabled:set" ],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用；09-22 加 hygiene:plan/apply（清理由 plan 只读 + apply 需二次确认）；09-25 加 backend:read/set（记忆后端二选一）+ mcp:install/uninstall/verify（一键装 MCP 记忆服务，用应用自带 node）",
  },
  { prefix: "rpa", count: 4, status: "in-features", file: "features/rpa-ipc.ts",
    channels: ["rpa:delete", "rpa:list", "rpa:record", "rpa:save"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "tasks", count: 5, status: "in-features", file: "features/tasks-ipc.ts",
    channels: ["tasks:add", "tasks:clear", "tasks:delete", "tasks:list", "tasks:update"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用；10-06 夜六轮加 clear（新回合开工清上一轮清单）",
  },
  { prefix: "scheduler", count: 4, status: "in-features", file: "features/scheduler-ipc.ts",
    channels: ["scheduler:delete", "scheduler:list", "scheduler:run", "scheduler:save"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "voice", count: 41, status: "in-features", file: "features/voice-ipc.ts",
    channels: ["voice:status","voice:settings-get","voice:settings-set","voice:start","voice:dictation-finish","voice:endpoint-now","voice:stop","voice:audio","voice:speak","voice:preview-voice","voice:hotkey-set","voice:hotkey-get","voice:wake-start","voice:wake-audio","voice:wake-reset","voice:wake-stop","voice:barge","voice:playback-done","voice:models-status","voice:zipvoice-install","voice:zipvoice-cancel","voice:kws-install","voice:kws-cancel","voice:kws-status","voice:profiles-list","voice:preset-list","voice:preset-apply","voice:profiles-import","voice:profiles-record","voice:profiles-save","voice:profiles-delete","voice:profiles-select","voice:profiles-preview","voice:models-install","voice:models-cancel","voice:models-import","voice:models-reveal","voice:models-uninstall","voice:mic-permission","voice:resource-set-enabled","voice:resource-delete","voice:resource-status"],
    note: "10-03 count 39 → 41：新增资源三态通道（启用/停用/删除）。原 count 与 channels 实际条数已不符（写 39 实列 38），一并订正为真实条数",
  },
  { prefix: "domains", count: 3, status: "in-features", file: "features/domains-ipc.ts",
    channels: ["domains:list", "domains:set-enabled", "domains:reload-hint"],
    note: "10-04 阶段 6 宿主域清单与启停。停用**真热插拔**（生成物持有 Fiber 句柄，可运行时 unmount/mount）；⛔ 但共享单例持有方（DOMAINS_NOT_HOT_UNLOADABLE，server/codexHome/mainWindow/toolsRoot 的主人）只能重启生效—— dispose() 撤不掉模块级变量。essential 域（electron/essential-domains.ts）承载身份/对话主链路/基础对话框，不可停用" },
  { prefix: "declared-plugins", count: 3, status: "in-features", file: "features/declared-plugins-ipc.ts",
    channels: ["declared-plugins:list", "declared-plugins:toggle", "declared-plugins:open-dirs"],
    note: "10-04 B 档 声明式插件（外部 JSON，**不含代码**）。⚠️ 刻意不加载 JS：Electron 主进程是特权域（safeStorage/BrowserWindow/全部 fs），第三方代码进来= 提权。dsh 是 CLI、插件与宿主本来平权，所以它没这层问题；本项目有三次 CSP/可信根安全实证，故只做配置层组合这一半。插槽即时生效，无需重启",
  },
  { prefix: "screenshot", count: 6, status: "in-features", file: "features/screenshot-ipc.ts",
    channels: ["screenshot:settings-get", "screenshot:settings-set", "screenshot:hotkey-set", "screenshot:capture", "screenshot:pick-dir", "screenshot:reveal"],
    note: "09-24 新增：隐藏窗口全屏 + 冻结帧框选，两种模式各绑一条全局快捷键（先注册成功才落盘）；框选覆盖层用独立 preload（dist-electron/overlay-preload.js，沙箱化、不用主桥）",
  },
  { prefix: "favorites", count: 7, status: "in-features", file: "features/favorites-ipc.ts",
    channels: ["favorites:list", "favorites:add", "favorites:update", "favorites:delete", "favorites:clear", "favorites:touch", "favorites:to-memory"],
    note: "09-24 新增：真相源 userData/favorites.json；删除只认显式 id 列表（批量管理仍是一次确认）；to-memory 先读后写追加到记忆层，单行限长 300 字",
  },
  { prefix: "history", count: 1, status: "in-features", file: "features/history-search-ipc.ts",
    channels: ["history:search"],
    note: "09-24 新增：顶栏 🔍 历史会话搜索。真相源 = rollout 原档（sessions/** + archived_sessions/**）；indexOf 快速否决 + >32MB 跳过计数 + mtime 倒序提前收工",
  },
];

/** 按通道（完整 channel 名）查所属域条目 */
export function domainOf(channel: string): IpcDomainEntry | undefined {
  const prefix = channel.split(":")[0];
  return IPC_DOMAINS.find((d) => d.prefix === prefix);
}

/** 仍在 electron/main.ts 待拆的域（in-main） */
export function domainsStillInMain(): IpcDomainEntry[] {
  return IPC_DOMAINS.filter((d) => d.status === "in-main");
}
