/**
 * IPC 域注册表（架构改造批 4 前置：channel → 所属模块的「接口在哪」查表）。
 *
 * 记账规则：
 *   · status=in-main    → handler 体仍在 electron/main.ts（待拆，账本 count 应 = main.ts 实际数）
 *   · status=in-features → 已拆到 electron/features/<file>（搬走 = 该域通道必须从 main.ts 消失）
 *   · status=shell      → 壳族基础设施（window/dialog/clipboard/fs/theme/notify/external/shell/awake/updates），留在 main 顶层不拆
 *                         （09-22：app 族 8 个通道已整体拆到 features/app-diagnostics.ts，从 shell 族移出）
 *   · count            → 该域 handler 总数（拆分前基线，搬走后不回填 0，账本永远记总量）
 *   · channels         → 已拆域的完整通道清单，供预检守卫【90】校验「搬干净没有」
 *
 * 每拆一个域：把 handler 体搬进 electron/features/<域>.ts 后，改这里 status=in-features、
 * file=features/<域>.ts、channels 填全 —— 预检【90】会盯着 main.ts 里该域通道数必须归零。
 */
export type IpcDomainStatus = "in-main" | "in-features" | "shell";

export interface IpcDomainEntry {
  /** 域前缀（channel 冒号前部分，如 relay / voice） */
  prefix: string;
  /** 该域 handler 总数（拆分前基线） */
  count: number;
  /** 现在在哪：in-main / in-features / shell */
  status: IpcDomainStatus;
  /** 所在文件：in-main|shell → "main.ts"；in-features → "features/<file>.ts" */
  file: string;
  /** 已拆域的完整通道清单（status=in-features 时必填） */
  channels?: string[];
  /** 备注（计划落点 / 拆分注意） */
  note?: string;
}

export const IPC_DOMAINS: IpcDomainEntry[] = [
  { prefix: "team-runs", count: 1, status: "in-features", file: "features/teams-agents-ipc.ts",
    channels: ["team-runs:list"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "team-threads", count: 2, status: "in-features", file: "features/teams-agents-ipc.ts",
    channels: ["team-threads:map", "team-threads:team-of"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "thread-runtime", count: 6, status: "in-features", file: "features/engine-ipc.ts",
    channels: ["thread-runtime:dispatch-owner", "thread-runtime:get", "thread-runtime:list", "thread-runtime:patch", "thread-runtime:release-dispatch", "thread-runtime:seed"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "agents", count: 9, status: "in-features", file: "features/teams-agents-ipc.ts",
    channels: ["agents:archive", "agents:catalog", "agents:delegated", "agents:delegated-of", "agents:invoke", "agents:notice", "agents:off-notice", "agents:thread-role", "agents:tool-description"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "theme", count: 1, status: "shell", file: "main.ts",
    channels: ["theme:apply"],
  },
  { prefix: "bot-binding", count: 2, status: "in-features", file: "features/im-channels-ipc.ts",
    channels: ["bot-binding:get", "bot-binding:set"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "bots", count: 2, status: "in-features", file: "features/im-channels-ipc.ts",
    channels: ["bots:get", "bots:set"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "bot-stream", count: 2, status: "in-features", file: "features/im-channels-ipc.ts",
    channels: ["bot-stream:get", "bot-stream:set"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "weixin", count: 5, status: "in-features", file: "features/im-channels-ipc.ts",
    channels: ["weixin:cancel-login", "weixin:logout", "weixin:poll-login", "weixin:start-login", "weixin:status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "telegram", count: 3, status: "in-features", file: "features/im-channels-ipc.ts",
    channels: ["telegram:connect", "telegram:logout", "telegram:status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "channels", count: 1, status: "in-features", file: "features/im-channels-ipc.ts",
    channels: ["channels:status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "feishu", count: 5, status: "in-features", file: "features/im-channels-ipc.ts",
    channels: ["feishu:connect", "feishu:logout", "feishu:qr-cancel", "feishu:qr-start", "feishu:qr-status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "dingtalk", count: 2, status: "in-features", file: "features/im-channels-ipc.ts",
    channels: ["dingtalk:connect", "dingtalk:logout"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "qq", count: 5, status: "in-features", file: "features/im-channels-ipc.ts",
    channels: ["qq:connect", "qq:logout", "qq:qr-cancel", "qq:qr-start", "qq:qr-status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "wecom-webhook", count: 3, status: "in-features", file: "features/im-channels-ipc.ts",
    channels: ["wecom-webhook:connect", "wecom-webhook:logout", "wecom-webhook:test"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "ponytail", count: 2, status: "in-features", file: "features/im-channels-ipc.ts",
    channels: ["ponytail:mode:get", "ponytail:mode:set"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "codex", count: 3, status: "in-features", file: "features/engine-ipc.ts",
    channels: ["codex:request", "codex:respond", "codex:set-active-thread"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "user", count: 1, status: "in-features", file: "features/user-ipc.ts",
    channels: ["user:name"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "app", count: 8, status: "in-features", file: "features/app-diagnostics.ts",
    channels: ["app:doctor", "app:engine-info", "app:home-dir", "app:perf-counters", "app:relaunch", "app:storage-clear", "app:storage-info", "app:userData"],
    note: "09-22 拆出：这 8 个通道全是「应用信息 / 环境自检 / 存储管理 / 重启」语义（不是壳族基础设施），整体搬进 features/app-diagnostics.ts 后从 shell 族移出",
  },
  { prefix: "capabilities", count: 1, status: "in-features", file: "features/user-ipc.ts",
    channels: ["capabilities:snapshot"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "window", count: 4, status: "shell", file: "main.ts",
    channels: ["window:popout-thread", "window:popout-close", "window:popout-id", "window:popout-list"],
    note: "09-24 从 preload 手写区迁进 manifest（登记面补全，守卫【2】按 channel 字面判登记）",
  },
  { prefix: "engine", count: 4, status: "in-features", file: "features/engine-ipc.ts",
    channels: ["engine:active-turns", "engine:check-update", "engine:perform-update", "engine:restart-log"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "builtin", count: 5, status: "in-features", file: "features/builtin-skills-ipc.ts",
    channels: ["builtin:describe-image", "builtin:generate-image", "builtin:probe", "builtin:read", "builtin:save"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "relay", count: 14, status: "in-features", file: "features/relay-ipc.ts",
    channels: ["relay:login", "relay:load-account", "relay:accounts", "relay:toggle-account", "relay:switch-account", "relay:remove-account", "relay:overview", "relay:create-key", "relay:select", "relay:key-billing", "relay:register", "relay:payment-plans", "relay:open-purchase", "relay:keys-all"],
    note: "09-21 拆出：跨域符号经 RelayIpcDeps 注入（模型域 4 个 + describeNetworkError + server 单例）；main.ts 的「启用/停用供应商」联动用导出的 readRelayStore/writeRelayStore 薄包装",
  },
  { prefix: "openai", count: 12, status: "in-features", file: "features/model-custom-ipc.ts",
    channels: ["openai:account-remove", "openai:account-switch", "openai:accounts", "openai:capture-login", "openai:import-file", "openai:login-cancel", "openai:login-start", "openai:login-status", "openai:models", "openai:set-proxy", "openai:toggle-account", "openai:usage"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "prompt", count: 1, status: "in-features", file: "features/connectors-mcp-ipc.ts",
    channels: ["prompt:enhance"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "terminal", count: 5, status: "in-features", file: "features/settings-app-ipc.ts",
    channels: ["terminal:input", "terminal:list", "terminal:ready", "terminal:resize", "terminal:restart"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "updates", count: 4, status: "in-features", file: "features/updates-ipc.ts",
    channels: ["updates:check", "updates:download", "updates:reveal", "updates:install"],
    note: "09-22 拆出：updates 全部 4 个更新链通道 + 权威状态 lastUpdateInfo / lastVerifiedUpdatePath",
  },
  { prefix: "plugin", count: 1, status: "in-features", file: "features/builtin-skills-ipc.ts",
    channels: ["plugin:validate"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "remote", count: 11, status: "in-features", file: "features/remote-ipc.ts",
    channels: ["remote:approve", "remote:deny", "remote:devices", "remote:pair-rotate", "remote:pair-state", "remote:qrcode", "remote:revoke", "remote:send", "remote:start", "remote:status", "remote:stop"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "bot", count: 7, status: "in-features", file: "features/im-channels-ipc.ts",
    channels: ["bot:approve", "bot:bind-consume", "bot:bind-qrcode", "bot:bind-status", "bot:deny", "bot:pair-state", "bot:revoke"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "notify", count: 1, status: "in-features", file: "features/shell-misc-ipc.ts",
    channels: ["notify:show"],
    note: "09-22 拆出：系统通知通道",
  },
  { prefix: "awake", count: 1, status: "in-features", file: "features/shell-misc-ipc.ts",
    channels: ["awake:set"],
    note: "09-22 拆出：防休眠通道（状态 awakeId 随迁）",
  },
  { prefix: "tools", count: 1, status: "in-features", file: "features/builtin-skills-ipc.ts",
    channels: ["tools:status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "runtime", count: 3, status: "in-features", file: "features/engine-ipc.ts",
    channels: ["runtime:install", "runtime:list", "runtime:uninstall"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "browser", count: 3, status: "in-features", file: "features/settings-app-ipc.ts",
    channels: ["browser:cloak-status", "browser:open-cloak", "browser:popout"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "git", count: 1, status: "in-features", file: "features/settings-app-ipc.ts",
    channels: ["git:diff"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "fs", count: 3, status: "in-features", file: "features/fs-ipc.ts",
    channels: ["fs:write", "fs:read", "fs:exists"],
    note: "09-22 拆出：fs 全部 3 个文件读写通道；isInsideTrustedRoots 经 ../main 活绑定且在 handler 内求值",
  },
  { prefix: "dialog", count: 5, status: "in-features", file: "features/dialog-ipc.ts",
    channels: ["dialog:directory", "dialog:directory-at", "dialog:images", "dialog:files", "dialog:ssh-key"],
    note: "09-22 拆出：dialog 全部 5 个文件选择通道；mainWindow/trustPicked 经 main 导出的活绑定取用",
  },
  { prefix: "skills", count: 8, status: "in-features", file: "features/builtin-skills-ipc.ts",
    channels: ["skills:import", "skills:local-list", "skills:local-remove", "skills:market-install", "skills:market-install-light", "skills:market-list", "skills:set-enabled", "skills:set-enabled-batch"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "skill-discipline", count: 1, status: "in-features", file: "features/builtin-skills-ipc.ts",
    channels: ["skill-discipline:get"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "plugins", count: 4, status: "in-features", file: "features/builtin-skills-ipc.ts",
    channels: ["plugins:market-install", "plugins:market-list", "plugins:set-enabled", "plugins:set-linked-enabled"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "hooks", count: 2, status: "in-features", file: "features/builtin-skills-ipc.ts",
    channels: ["hooks:set-enabled", "hooks:trust"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "connectors", count: 7, status: "in-features", file: "features/connectors-mcp-ipc.ts",
    channels: ["connectors:list", "connectors:oauth-cancel", "connectors:oauth-start", "connectors:remove", "connectors:save", "connectors:set-enabled", "connectors:templates"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "mcp-servers", count: 4, status: "in-features", file: "features/connectors-mcp-ipc.ts",
    channels: ["mcp-servers:overrides", "mcp-servers:permissions", "mcp-servers:set-enabled", "mcp-servers:set-tool-permission"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "personalization", count: 6, status: "in-features", file: "features/settings-app-ipc.ts",
    channels: ["personalization:mark-greeted", "personalization:read", "personalization:save", "personalization:save-identity", "personalization:setNickname", "personalization:verify"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "appSettings", count: 2, status: "in-features", file: "features/settings-app-ipc.ts",
    channels: ["appSettings:read", "appSettings:save"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "model-specs", count: 1, status: "in-features", file: "features/model-custom-ipc.ts",
    channels: ["model-specs:read"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "ssh", count: 12, status: "in-features", file: "features/settings-app-ipc.ts",
    channels: ["ssh:delete", "ssh:exec", "ssh:export", "ssh:import", "ssh:list", "ssh:save", "ssh:session-close", "ssh:session-open", "ssh:session-resize", "ssh:session-write", "ssh:set-enabled", "ssh:test"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "threads", count: 5, status: "in-features", file: "features/engine-ipc.ts",
    channels: ["threads:export", "threads:export-markdown", "threads:import", "threads:import-conversation", "threads:preview-conversation"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "commands", count: 5, status: "in-features", file: "features/teams-agents-ipc.ts",
    channels: ["commands:delete", "commands:expand", "commands:list", "commands:read", "commands:save"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "subagents", count: 4, status: "in-features", file: "features/teams-agents-ipc.ts",
    channels: ["subagents:invoke", "subagents:list", "subagents:remove", "subagents:save"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "teams", count: 9, status: "in-features", file: "features/teams-agents-ipc.ts",
    channels: ["teams:invoke-member", "teams:list", "teams:member-session", "teams:remove", "teams:reset-defaults", "teams:save", "teams:session-config", "teams:start-session", "teams:tools"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "clipboard", count: 4, status: "in-features", file: "features/clipboard-ipc.ts",
    channels: ["clipboard:image", "clipboard:write", "clipboard:write-image", "clipboard:read-files"],
    note: "09-22 拆出：clipboard 全部 4 个剪贴板通道；imagesDir 改为 handler 内惰性求值（app.getPath 不落模块顶层）",
  },
  { prefix: "pasted-text", count: 3, status: "in-features", file: "features/settings-app-ipc.ts",
    channels: ["pasted-text:read", "pasted-text:save", "pasted-text:update"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "external", count: 1, status: "in-features", file: "features/shell-misc-ipc.ts",
    channels: ["external:open"],
    note: "09-22 拆出：外链打开（filePreviewAllowed 活绑定）",
  },
  { prefix: "shell", count: 1, status: "in-features", file: "features/shell-misc-ipc.ts",
    channels: ["shell:reveal"],
    note: "09-22 拆出：定位文件（isInsideOrEqualTrustedRoots 活绑定）",
  },
  { prefix: "scratch", count: 1, status: "in-features", file: "features/settings-app-ipc.ts",
    channels: ["scratch:create"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "custom-model", count: 12, status: "in-features", file: "features/model-custom-ipc.ts",
    channels: ["custom-model:apply", "custom-model:list", "custom-model:probe", "custom-model:read", "custom-model:remove", "custom-model:remove-model", "custom-model:save", "custom-model:select", "custom-model:set-effort", "custom-model:set-enabled", "custom-model:set-model", "custom-model:upsert-model"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "bridge", count: 1, status: "in-features", file: "features/engine-ipc.ts",
    channels: ["bridge:status"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "channel-bot", count: 3, status: "in-features", file: "features/im-channels-ipc.ts",
    channels: ["channel-bot:read", "channel-bot:save", "channel-bot:test"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "memory", count: 21, status: "in-features", file: "features/memory-rpa-ipc.ts",
    channels: ["memory:backend:read", "memory:backend:set", "memory:delete", "memory:distill", "memory:gateway:read", "memory:gateway:save", "memory:gateway:test", "memory:hygiene:apply", "memory:hygiene:plan", "memory:layers:context", "memory:layers:read", "memory:layers:write", "memory:list", "memory:mode-read", "memory:mode-set", "memory:recall", "memory:reset", "memory:save", "memory:search", "memory:workspace-enabled:read", "memory:workspace-enabled:set"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用；09-22 加 hygiene:plan/apply（清理由 plan 只读 + apply 需二次确认）；09-25 加 backend:read/set（记忆后端二选一，装在设置页「记忆」里）",
  },
  { prefix: "rpa", count: 4, status: "in-features", file: "features/memory-rpa-ipc.ts",
    channels: ["rpa:delete", "rpa:list", "rpa:record", "rpa:save"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "tasks", count: 4, status: "in-features", file: "features/memory-rpa-ipc.ts",
    channels: ["tasks:add", "tasks:delete", "tasks:list", "tasks:update"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "scheduler", count: 4, status: "in-features", file: "features/memory-rpa-ipc.ts",
    channels: ["scheduler:delete", "scheduler:list", "scheduler:run", "scheduler:save"],
    note: "09-21 拆出：跨域符号经 main 导出的活绑定取用",
  },
  { prefix: "voice", count: 39, status: "in-features", file: "features/voice-ipc.ts",
    channels: ["voice:status","voice:settings-get","voice:settings-set","voice:start","voice:dictation-finish","voice:endpoint-now","voice:stop","voice:audio","voice:speak","voice:preview-voice","voice:hotkey-set","voice:hotkey-get","voice:wake-start","voice:wake-audio","voice:wake-reset","voice:wake-stop","voice:barge","voice:playback-done","voice:models-status","voice:zipvoice-install","voice:zipvoice-cancel","voice:kws-install","voice:kws-cancel","voice:kws-status","voice:profiles-list","voice:preset-list","voice:preset-apply","voice:profiles-import","voice:profiles-record","voice:profiles-save","voice:profiles-delete","voice:profiles-select","voice:profiles-preview","voice:models-install","voice:models-cancel","voice:models-import","voice:models-reveal","voice:models-uninstall","voice:mic-permission"],
  },
  { prefix: "screenshot", count: 6, status: "in-features", file: "features/screenshot-favorites-ipc.ts",
    channels: ["screenshot:settings-get", "screenshot:settings-set", "screenshot:hotkey-set", "screenshot:capture", "screenshot:pick-dir", "screenshot:reveal"],
    note: "09-24 新增：隐藏窗口全屏 + 冻结帧框选，两种模式各绑一条全局快捷键（先注册成功才落盘）；框选覆盖层用独立 preload（dist-electron/overlay-preload.js，沙箱化、不用主桥）",
  },
  { prefix: "favorites", count: 7, status: "in-features", file: "features/screenshot-favorites-ipc.ts",
    channels: ["favorites:list", "favorites:add", "favorites:update", "favorites:delete", "favorites:clear", "favorites:touch", "favorites:to-memory"],
    note: "09-24 新增：真相源 userData/favorites.json；删除只认显式 id 列表（批量管理仍是一次确认）；to-memory 先读后写追加到记忆层，单行限长 300 字",
  },
  { prefix: "history", count: 1, status: "in-features", file: "features/history-search-ipc.ts",
    channels: ["history:search"],
    note: "09-24 新增：顶栏 🔍 历史会话搜索。真相源 = rollout 原档（sessions/** + archived_sessions/**）；indexOf 快速否决 + >32MB 跳过计数 + mtime 倒序提前收工",
  },
];

/** 按通道（完整 channel 名）查所属域条目 */
export function domainOf(channel: string): IpcDomainEntry | undefined {
  const prefix = channel.split(":")[0];
  return IPC_DOMAINS.find((d) => d.prefix === prefix);
}

/** 仍在 electron/main.ts 待拆的域（in-main） */
export function domainsStillInMain(): IpcDomainEntry[] {
  return IPC_DOMAINS.filter((d) => d.status === "in-main");
}
