/**
 * 自动生成，请勿手改 —— useHarnessApp 内顶层声明在 bag 上的类型。
 *
 * 作用：各 part 的 bag 参数标注为本接口后，跨段引用（bag.X）保留具体类型
 * ⇒ 消除 TS7006（隐式 any）级联。由 .workbuddy/tmp/gen-bag-types.cjs 用
 * TypeChecker 在**切分前的原文件**上推断而来（纯类型声明，零运行时开销）。
 */
import type * as React from "react";
import type { RateLimitCtx, BotEntry } from "./types";
import type { FavoriteRequest } from "../../../lib/favorite-bridge";

export interface Bag {
  serverStatus: string;
  setServerStatus: React.Dispatch<React.SetStateAction<string>>;
  popoutThreadId: string | null;
  setPopoutThreadId: React.Dispatch<React.SetStateAction<string | null>>;
  poppedOutThreadIds: Set<string>;
  setPoppedOutThreadIds: React.Dispatch<React.SetStateAction<Set<string>>>;
  refreshPoppedOut: () => void;
  showLogin: boolean;
  setShowLogin: React.Dispatch<React.SetStateAction<boolean>>;
  accountSwitchThreadRef: React.RefObject<string | null>;
  modelId: string;
  setModelId: React.Dispatch<React.SetStateAction<string>>;
  effort: string;
  setEffort: React.Dispatch<React.SetStateAction<string>>;
  bootReady: boolean;
  setBootReady: React.Dispatch<React.SetStateAction<boolean>>;
  threadsLoading: boolean;
  setThreadsLoading: React.Dispatch<React.SetStateAction<boolean>>;
  threads: import("../../app-view/types.ts").Thread[];
  setThreads: React.Dispatch<React.SetStateAction<import("../../app-view/types.ts").Thread[]>>;
  thread: import("../../app-view/types.ts").Thread | null;
  setThread: React.Dispatch<React.SetStateAction<import("../../app-view/types.ts").Thread | null>>;
  switchStartRef: React.RefObject<number>;
  switchModeRef: React.RefObject<"cached" | "fresh">;
  switchTurnsRef: React.RefObject<number>;
  scrollMemoRef: React.RefObject<Map<string, number>>;
  threadRef: React.RefObject<import("../../app-view/types.ts").Thread | null>;
  popoutThreadIdRef: React.RefObject<string | null>;
  threadsRef: React.RefObject<import("../../app-view/types.ts").Thread[]>;
  engineRestartedRef: React.RefObject<boolean>;
  sendingRef: React.RefObject<boolean>;
  activeTurnIdRef: React.RefObject<string | null>;
  activeTurnId: string | null;
  setActiveTurnId: React.Dispatch<React.SetStateAction<string | null>>;
  runningThreadIds: Set<string>;
  setRunningThreadIds: React.Dispatch<React.SetStateAction<Set<string>>>;
  runningThreadIdsRef: React.RefObject<Set<string>>;
  runningTurnIdsRef: React.RefObject<Map<string, string>>;
  runningStartedAtRef: React.RefObject<Map<string, number>>;
  markThreadRunning: (threadId: string, turnId?: string | undefined, startedAt?: number) => void;
  markThreadStopped: (threadId?: string | undefined) => void;
  clearRunningThreads: () => void;
  finishedTurnIdsRef: React.RefObject<Set<string>>;
  rememberFinishedTurn: (turnId: string) => void;
  manualStopRef: React.RefObject<Map<string, string>>;
  needsFullReloadRef: React.RefObject<Set<string>>;
  unreadDoneIds: Set<string>;
  setUnreadDoneIds: React.Dispatch<React.SetStateAction<Set<string>>>;
  unreadDoneIdsRef: React.RefObject<Set<string>>;
  markThreadDoneUnread: (threadId?: string | undefined) => void;
  clearThreadDoneUnread: (threadId?: string | undefined) => void;
  workspace: string;
  setWorkspace: React.Dispatch<React.SetStateAction<string>>;
  workspaceRef: React.RefObject<string>;
  prompt: string;
  setPrompt: React.Dispatch<React.SetStateAction<string>>;
  promptRef: React.RefObject<string>;
  draftThreadRef: React.RefObject<string | null>;
  draftJustRestoredRef: React.RefObject<boolean>;
  voiceDictating: boolean;
  setVoiceDictating: React.Dispatch<React.SetStateAction<boolean>>;
  dictationBaseRef: React.RefObject<string>;
  /** 上一次写进输入框的听写字幕（判断用户期间是否动过输入框的位标，见 lib/dictation-merge.mjs） */
  dictationWrittenRef: React.RefObject<string>;
  attachmentMenuOpen: boolean;
  setAttachmentMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  attachSubmenu: "none" | "files" | "thread-files" | "experts" | "skills" | "connectors" | "favorites";
  setAttachSubmenu: React.Dispatch<React.SetStateAction<"none" | "files" | "thread-files" | "experts" | "skills" | "connectors" | "favorites">>;
  favoriteQuery: string;
  setFavoriteQuery: React.Dispatch<React.SetStateAction<string>>;
  threadFileQuery: string;
  setThreadFileQuery: React.Dispatch<React.SetStateAction<string>>;
  expertQuery: string;
  setExpertQuery: React.Dispatch<React.SetStateAction<string>>;
  quickMenuRef: React.RefObject<HTMLDivElement | null>;
  quickMenuPanelRef: React.RefObject<HTMLDivElement | null>;
  quickMenuFlipUp: boolean;
  setQuickMenuFlipUp: React.Dispatch<React.SetStateAction<boolean>>;
  submenuFlip: boolean;
  setSubmenuFlip: React.Dispatch<React.SetStateAction<boolean>>;
  submenuTop: number;
  setSubmenuTop: React.Dispatch<React.SetStateAction<number>>;
  quickMenuViewport: { width: number; height: number; };
  setQuickMenuViewport: React.Dispatch<React.SetStateAction<{ width: number; height: number; }>>;
  submenuHoverTimer: React.RefObject<number | null>;
  submenuCloseTimer: React.RefObject<number | null>;
  scheduleSubmenu: (target: "files" | "thread-files" | "experts" | "skills" | "connectors" | "favorites") => void;
  scheduleSubmenuClose: () => void;
  plusSpinTick: number;
  setPlusSpinTick: React.Dispatch<React.SetStateAction<number>>;
  enhanceBusy: boolean;
  setEnhanceBusy: React.Dispatch<React.SetStateAction<boolean>>;
  enhanceBackupRef: React.RefObject<string | null>;
  enhanceRunIdRef: React.RefObject<number>;
  hasEnhanceBackup: boolean;
  setHasEnhanceBackup: React.Dispatch<React.SetStateAction<boolean>>;
  enhanceHint: string | null;
  setEnhanceHint: React.Dispatch<React.SetStateAction<string | null>>;
  enhanceHintTimerRef: React.RefObject<number | null>;
  lastEnhanceHintRef: React.RefObject<string | undefined>;
  enhanceSendCountRef: React.RefObject<number>;
  enhanceHintAfterSendRef: React.RefObject<boolean>;
  enhanceLongFiredRef: React.RefObject<boolean>;
  enhanceHintFiredAtRef: React.RefObject<number>;
  attachedFiles: string[];
  skillMenuOpen: boolean;
  setSkillMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  skillQuery: string;
  setSkillQuery: React.Dispatch<React.SetStateAction<string>>;
  selectedSkills: { name: string; description: string; }[];
  setSelectedSkills: React.Dispatch<React.SetStateAction<{ name: string; description: string; }[]>>;
  localSkills: LocalSkillEntry[];
  setLocalSkills: React.Dispatch<React.SetStateAction<LocalSkillEntry[]>>;
  marketSkills: MarketSkillEntry[];
  setMarketSkills: React.Dispatch<React.SetStateAction<MarketSkillEntry[]>>;
  marketLoading: boolean;
  setMarketLoading: React.Dispatch<React.SetStateAction<boolean>>;
  marketTotal: number;
  setMarketTotal: React.Dispatch<React.SetStateAction<number>>;
  marketPage: number;
  setMarketPage: React.Dispatch<React.SetStateAction<number>>;
  marketPageSize: number;
  installingMarketSkill: string | null;
  setInstallingMarketSkill: React.Dispatch<React.SetStateAction<string | null>>;
  pluginInstall: import("../../../lib/plugin-install-state.ts").PluginInstallState | null;
  setPluginInstall: React.Dispatch<React.SetStateAction<import("../../../lib/plugin-install-state.ts").PluginInstallState | null>>;
  pluginMarketItems: PluginMarketEntry[];
  setPluginMarketItems: React.Dispatch<React.SetStateAction<PluginMarketEntry[]>>;
  pluginMarketLoading: boolean;
  setPluginMarketLoading: React.Dispatch<React.SetStateAction<boolean>>;
  pluginMarketTotal: number;
  setPluginMarketTotal: React.Dispatch<React.SetStateAction<number>>;
  pluginMarketPage: number;
  setPluginMarketPage: React.Dispatch<React.SetStateAction<number>>;
  pluginMarketPageSize: number;
  installingMarketPlugin: string | null;
  setInstallingMarketPlugin: React.Dispatch<React.SetStateAction<string | null>>;
  pluginMarketCategory: string;
  setPluginMarketCategory: React.Dispatch<React.SetStateAction<string>>;
  pluginMarketSearch: string;
  setPluginMarketSearch: React.Dispatch<React.SetStateAction<string>>;
  mcpMarketCategory: string;
  setMcpMarketCategory: React.Dispatch<React.SetStateAction<string>>;
  mcpMarketSearch: string;
  setMcpMarketSearch: React.Dispatch<React.SetStateAction<string>>;
  marketPreview: import("../../../lib/market-preview-state.ts").MarketPreviewState | null;
  setMarketPreview: React.Dispatch<React.SetStateAction<import("../../../lib/market-preview-state.ts").MarketPreviewState | null>>;
  browserOpenReq: { url: string; seq: number; } | null;
  setBrowserOpenReq: React.Dispatch<React.SetStateAction<{ url: string; seq: number; } | null>>;
  openInBrowserPane: (url: string) => void;
  relayBusy: boolean;
  setRelayBusy: React.Dispatch<React.SetStateAction<boolean>>;
  relayActive: import("../../../lib/relay.ts").RelayActive | null;
  setRelayActive: React.Dispatch<React.SetStateAction<import("../../../lib/relay.ts").RelayActive | null>>;
  openaiActiveAcct: string | null;
  setOpenaiActiveAcct: React.Dispatch<React.SetStateAction<string | null>>;
  skillInstall: import("../../../lib/skill-install-state.ts").SkillInstallState | null;
  setSkillInstall: React.Dispatch<React.SetStateAction<import("../../../lib/skill-install-state.ts").SkillInstallState | null>>;
  skillRemove: import("../../../lib/skill-remove-state.ts").SkillRemoveState | null;
  setSkillRemove: React.Dispatch<React.SetStateAction<import("../../../lib/skill-remove-state.ts").SkillRemoveState | null>>;
  connectorMenuOpen: boolean;
  setConnectorMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  connectors: ConnectorEntry[];
  setConnectors: React.Dispatch<React.SetStateAction<ConnectorEntry[]>>;
  connectorDraft: ConnectorDraft;
  setConnectorDraft: React.Dispatch<React.SetStateAction<ConnectorDraft>>;
  connectorEditorOpen: boolean;
  setConnectorEditorOpen: React.Dispatch<React.SetStateAction<boolean>>;
  connectorSaving: boolean;
  setConnectorSaving: React.Dispatch<React.SetStateAction<boolean>>;
  connectorSecret: string;
  setConnectorSecret: React.Dispatch<React.SetStateAction<string>>;
  connectorTemplates: ConnectorTemplate[];
  setConnectorTemplates: React.Dispatch<React.SetStateAction<ConnectorTemplate[]>>;
  connectorTemplateModal: ConnectorTemplate | null;
  setConnectorTemplateModal: React.Dispatch<React.SetStateAction<ConnectorTemplate | null>>;
  connectorOAuth: ConnectorOAuthEvent | null;
  setConnectorOAuth: React.Dispatch<React.SetStateAction<ConnectorOAuthEvent | null>>;
  connectorTemplateValues: Record<string, string>;
  setConnectorTemplateValues: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  connectorTemplateSaving: boolean;
  setConnectorTemplateSaving: React.Dispatch<React.SetStateAction<boolean>>;
  memoryConfigOpen: boolean;
  setMemoryConfigOpen: React.Dispatch<React.SetStateAction<boolean>>;
  contextOpen: boolean;
  setContextOpen: React.Dispatch<React.SetStateAction<boolean>>;
  contextQuery: string;
  setContextQuery: React.Dispatch<React.SetStateAction<string>>;
  contextItems: { id: string; role: "用户" | "Codex"; text: string; }[];
  setContextItems: React.Dispatch<React.SetStateAction<{ id: string; role: "用户" | "Codex"; text: string; }[]>>;
  quoteItem: { id: string; text: string; } | null;
  setQuoteItem: React.Dispatch<React.SetStateAction<{ id: string; text: string; } | null>>;
  images: string[];
  setImages: React.Dispatch<React.SetStateAction<string[]>>;
  loading: boolean;
  setLoading: React.Dispatch<React.SetStateAction<boolean>>;
  sending: boolean;
  setSending: React.Dispatch<React.SetStateAction<boolean>>;
  sendInFlightRef: React.RefObject<boolean>;
  rateLimitRetries: Record<string, { attempt: number; retryAt: number; }>;
  setRateLimitRetries: React.Dispatch<React.SetStateAction<Record<string, { attempt: number; retryAt: number; }>>>;
  upstreamRetries: Record<string, { no: number; total: number; }>;
  setUpstreamRetries: React.Dispatch<React.SetStateAction<Record<string, { no: number; total: number; }>>>;
  setRetryEntry: (threadId: string, entry: { attempt: number; retryAt: number; } | null) => void;
  retryContextsRef: React.RefObject<Map<string, RateLimitCtx>>;
  rateLimitAttemptsRef: React.RefObject<Map<string, number>>;
  rateLimitTimersRef: React.RefObject<Map<string, number>>;
  retryGatesRef: React.RefObject<Map<string, Promise<unknown>>>;
  effortFallbackRef: React.RefObject<{ threadId: string; input: any[]; model: string; effort: string | null; personality: string | null; } | null>;
  autoContinueLogRef: React.RefObject<Map<string, { count: number; firstAt: number; }>>;
  setRateLimitTick: React.Dispatch<React.SetStateAction<number>>;
  clearRateLimitTimer: (threadId?: string | undefined) => void;
  armRateLimitRetry: (threadId: string, ctx: RateLimitCtx) => void;
  recoverRateLimitCtx: (threadId: string, turn: any) => RateLimitCtx | null;
  ensureRateLimitCtx: (threadId: string, turn: any) => boolean;
  armRetryForQueueRelease: (threadId: string | null | undefined, entryInput: any[] | undefined) => void;
  resetSessionRetryState: (threadId: string) => void;
  cancelRateLimitRetry: (threadId?: string | undefined, silent?: boolean) => void;
  executeRateLimitRetry: (threadId: string) => Promise<void>;
  executeEffortFallbackRetry: () => Promise<void>;
  scheduleRateLimitRetry: (threadId: string, attempt: number) => void;
  compactPendingRef: React.RefObject<Set<string>>;
  interrupting: boolean;
  setInterrupting: React.Dispatch<React.SetStateAction<boolean>>;
  optimisticInput: import("../../../lib/thread-item.ts").ThreadItem | null;
  setOptimisticInput: React.Dispatch<React.SetStateAction<import("../../../lib/thread-item.ts").ThreadItem | null>>;
  optimisticTurnIdRef: React.RefObject<string | null>;
  optimisticBaselineRef: React.RefObject<{ threadId: string | null; turnIds: Set<string>; }>;
  sawRunningTurnRef: React.RefObject<boolean>;
  optimisticConfirmed: boolean;
  openingThread: string | null;
  setOpeningThread: React.Dispatch<React.SetStateAction<string | null>>;
  pending: import("../../app-view/types.ts").PendingRequest[];
  setPending: React.Dispatch<React.SetStateAction<import("../../app-view/types.ts").PendingRequest[]>>;
  diff: string;
  setDiff: React.Dispatch<React.SetStateAction<string>>;
  tokenUsage: any;
  setTokenUsage: React.Dispatch<any>;
  tokenUsageRef: React.RefObject<any>;
  tokenUsageByThreadRef: React.RefObject<Map<string, any>>;
  persistTokenUsageSnapshot: (threadId: string, usage: any) => void;
  inheritTokenUsageSnapshot: (fromThreadId: string, toThreadId: string) => void;
  tokenUsageTotalsRef: React.RefObject<Map<string, import("../../status/Status.tsx").UsageCounterSnapshot>>;
  derivedTokenUsageRef: React.RefObject<Map<string, any>>;
  normalizeTokenUsage: (raw: any, threadId?: string | undefined) => any;
  turnStartedAtRef: React.RefObject<Map<string, number>>;
  activeModelRef: React.RefObject<string>;
  usageStats: import("../../../lib/usage-stats.ts").UsageStats;
  setUsageStats: React.Dispatch<React.SetStateAction<import("../../../lib/usage-stats.ts").UsageStats>>;
  streamRafRef: React.RefObject<number>;
  pendingDeltaRef: React.RefObject<{ method: string; params: any; }[]>;
  lastFlushAtRef: React.RefObject<number>;
  rightOpen: boolean;
  setRightOpen: React.Dispatch<React.SetStateAction<boolean>>;
  desktopAuto: boolean;
  setDesktopAuto: React.Dispatch<React.SetStateAction<boolean>>;
  browserAuto: boolean;
  setBrowserAuto: React.Dispatch<React.SetStateAction<boolean>>;
  autoCompactRatio: number;
  setAutoCompactRatio: React.Dispatch<React.SetStateAction<number>>;
  hardwareAccel: "auto" | "force" | "off";
  setHardwareAccel: React.Dispatch<React.SetStateAction<"auto" | "force" | "off">>;
  downloadSource: "auto" | "mirror" | "ghproxy" | "ghfast" | "direct" | "proxy";
  setDownloadSource: React.Dispatch<React.SetStateAction<"auto" | "mirror" | "ghproxy" | "ghfast" | "direct" | "proxy">>;
  adaptiveTone: boolean;
  setAdaptiveTone: React.Dispatch<React.SetStateAction<boolean>>;
  restartPending: boolean;
  setRestartPending: React.Dispatch<React.SetStateAction<boolean>>;
  sshServers: SshServer[];
  setSshServers: React.Dispatch<React.SetStateAction<SshServer[]>>;
  sshLoaded: boolean;
  setSshLoaded: React.Dispatch<React.SetStateAction<boolean>>;
  sshBusyId: string | null;
  setSshBusyId: React.Dispatch<React.SetStateAction<string | null>>;
  sshTestingId: string | null;
  setSshTestingId: React.Dispatch<React.SetStateAction<string | null>>;
  sshDraft: SshServer | null;
  setSshDraft: React.Dispatch<React.SetStateAction<SshServer | null>>;
  sshSaving: boolean;
  setSshSaving: React.Dispatch<React.SetStateAction<boolean>>;
  sshQuery: string;
  setSshQuery: React.Dispatch<React.SetStateAction<string>>;
  sshFilter: "off" | "all" | "on" | "star";
  setSshFilter: React.Dispatch<React.SetStateAction<"off" | "all" | "on" | "star">>;
  sshChecked: string[];
  setSshChecked: React.Dispatch<React.SetStateAction<string[]>>;
  sshBatchBusy: boolean;
  setSshBatchBusy: React.Dispatch<React.SetStateAction<boolean>>;
  sshTerminal: SshServer | null;
  setSshTerminal: React.Dispatch<React.SetStateAction<SshServer | null>>;
  sshExecTarget: SshServer | null;
  setSshExecTarget: React.Dispatch<React.SetStateAction<SshServer | null>>;
  sshEditorTest: { ok: boolean; message: string; } | null;
  setSshEditorTest: React.Dispatch<React.SetStateAction<{ ok: boolean; message: string; } | null>>;
  toggleDesktopAuto: (next: boolean) => void;
  toggleBrowserAuto: (next: boolean) => void;
  changeAdaptiveTone: (next: boolean) => void;
  changeHardwareAccel: (next: "auto" | "force" | "off") => void;
  changeDownloadSource: (next: "auto" | "mirror" | "ghproxy" | "ghfast" | "direct" | "proxy") => void;
  engineVersion: string;
  setEngineVersion: React.Dispatch<React.SetStateAction<string>>;
  engineCheck: { state: "idle" | "checking" | "latest" | "available" | "error"; latest?: string | undefined; message?: string | undefined; };
  setEngineCheck: React.Dispatch<React.SetStateAction<{ state: "idle" | "checking" | "latest" | "available" | "error"; latest?: string | undefined; message?: string | undefined; }>>;
  engineUpdating: boolean;
  setEngineUpdating: React.Dispatch<React.SetStateAction<boolean>>;
  engineUpdateLog: string[];
  setEngineUpdateLog: React.Dispatch<React.SetStateAction<string[]>>;
  engineUpdatePercent: number | null;
  setEngineUpdatePercent: React.Dispatch<React.SetStateAction<number | null>>;
  engineUpdateStageText: string;
  setEngineUpdateStageText: React.Dispatch<React.SetStateAction<string>>;
  engineUpdateResult: { ok: boolean; message: string; } | null;
  setEngineUpdateResult: React.Dispatch<React.SetStateAction<{ ok: boolean; message: string; } | null>>;
  relaunchCountdown: number | null;
  setRelaunchCountdown: React.Dispatch<React.SetStateAction<number | null>>;
  checkEngineUpdateNow: () => Promise<void>;
  performEngineUpdateNow: () => Promise<void>;
  emptySshJump: () => SshJumpHost;
  emptySshDraft: () => SshServer;
  sshDraftIssues: (draft: SshServer) => string[];
  sshDraftValid: (draft: SshServer) => boolean;
  sshVisible: SshServer[];
  sshCheckedSet: Set<string>;
  sshToggleChecked: (id: string) => void;
  saveSshEntry: () => Promise<void>;
  testSshDraft: () => Promise<void>;
  toggleSshEntry: (server: SshServer, next: boolean) => Promise<void>;
  toggleSshBatch: (next: boolean) => Promise<void>;
  testSshEntry: (server: SshServer, silent?: boolean) => Promise<SshTestResult | { ok: false; error: any; }>;
  testSshBatch: () => Promise<void>;
  removeSshEntries: (ids: string[]) => Promise<void>;
  duplicateSshEntry: (server: SshServer) => Promise<void>;
  toggleSshFavorite: (server: SshServer) => Promise<void>;
  exportSshEntries: (includeSecrets: boolean) => Promise<void>;
  importSshEntries: () => Promise<void>;
  sidebarCollapsed: boolean;
  setSidebarCollapsed: React.Dispatch<React.SetStateAction<boolean>>;
  rightTab: string;
  setRightTab: React.Dispatch<React.SetStateAction<string>>;
  openTabs: { key: string; name: string; }[];
  setOpenTabs: React.Dispatch<React.SetStateAction<{ key: string; name: string; }[]>>;
  recentlyClosed: { key: string; name: string; at: number; }[];
  setRecentlyClosed: React.Dispatch<React.SetStateAction<{ key: string; name: string; at: number; }[]>>;
  switcherOpen: boolean;
  setSwitcherOpen: React.Dispatch<React.SetStateAction<boolean>>;
  switcherQuery: string;
  setSwitcherQuery: React.Dispatch<React.SetStateAction<string>>;
  goalsExpanded: boolean;
  setGoalsExpanded: React.Dispatch<React.SetStateAction<boolean>>;
  goalsDocked: boolean;
  setGoalsDocked: React.Dispatch<React.SetStateAction<boolean>>;
  paletteOpen: boolean;
  setPaletteOpen: React.Dispatch<React.SetStateAction<boolean>>;
  paletteQuery: string;
  setPaletteQuery: React.Dispatch<React.SetStateAction<string>>;
  paletteTab: "files" | "all" | "ops" | "tasks";
  setPaletteTab: React.Dispatch<React.SetStateAction<"files" | "all" | "ops" | "tasks">>;
  keepAwake: boolean;
  setKeepAwake: React.Dispatch<React.SetStateAction<boolean>>;
  ctxMenuOpen: boolean;
  setCtxMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  skillHubCategory: string;
  setSkillHubCategory: React.Dispatch<React.SetStateAction<string>>;
  skillHubSearch: string;
  setSkillHubSearch: React.Dispatch<React.SetStateAction<string>>;
  skillHubFilterCategory: string;
  setSkillHubFilterCategory: React.Dispatch<React.SetStateAction<string>>;
  skillsManageOnly: boolean;
  setSkillsManageOnly: React.Dispatch<React.SetStateAction<boolean>>;
  connectorSearch: string;
  setConnectorSearch: React.Dispatch<React.SetStateAction<string>>;
  connectorsManageOnly: boolean;
  setConnectorsManageOnly: React.Dispatch<React.SetStateAction<boolean>>;
  connectorChecked: string[];
  setConnectorChecked: React.Dispatch<React.SetStateAction<string[]>>;
  connectorStatusBusy: string | null;
  setConnectorStatusBusy: React.Dispatch<React.SetStateAction<string | null>>;
  connectorBatchBusy: "enable" | "disable" | null;
  setConnectorBatchBusy: React.Dispatch<React.SetStateAction<"enable" | "disable" | null>>;
  mcpOverrides: Record<string, boolean>;
  setMcpOverrides: React.Dispatch<React.SetStateAction<Record<string, boolean>>>;
  mcpToolPermissions: Record<string, Record<string, "deny" | "ask" | "allow">>;
  setMcpToolPermissions: React.Dispatch<React.SetStateAction<Record<string, Record<string, "deny" | "ask" | "allow">>>>;
  mcpServerChecked: string[];
  setMcpServerChecked: React.Dispatch<React.SetStateAction<string[]>>;
  mcpServerStatusBusy: string | null;
  setMcpServerStatusBusy: React.Dispatch<React.SetStateAction<string | null>>;
  mcpServerBatchBusy: "enable" | "disable" | null;
  setMcpServerBatchBusy: React.Dispatch<React.SetStateAction<"enable" | "disable" | null>>;
  mcpServerSearch: string;
  setMcpServerSearch: React.Dispatch<React.SetStateAction<string>>;
  subAgents: SubAgentEntry[];
  setSubAgents: React.Dispatch<React.SetStateAction<SubAgentEntry[]>>;
  subAgentDraft: SubAgentEntry | null;
  setSubAgentDraft: React.Dispatch<React.SetStateAction<SubAgentEntry | null>>;
  subAgentEditorOpen: boolean;
  setSubAgentEditorOpen: React.Dispatch<React.SetStateAction<boolean>>;
  subAgentRunning: string | null;
  setSubAgentRunning: React.Dispatch<React.SetStateAction<string | null>>;
  rpaRunning: string | null;
  setRpaRunning: React.Dispatch<React.SetStateAction<string | null>>;
  agentAsk: { threadId: string; question: string; options: string[]; recommended: string | null; allowFree: boolean; resolve: (answer: string) => void; } | null;
  setAgentAsk: React.Dispatch<React.SetStateAction<{ threadId: string; question: string; options: string[]; recommended: string | null; allowFree: boolean; resolve: (answer: string) => void; } | null>>;
  rpaRecipes: any[];
  setRpaRecipes: React.Dispatch<React.SetStateAction<any[]>>;
  taskList: any[];
  setTaskList: React.Dispatch<React.SetStateAction<any[]>>;
  threadPermPushAtRef: React.RefObject<Map<string, number>>;
  appPromptInputRef: React.RefObject<HTMLInputElement | HTMLTextAreaElement | null>;
  appConfirm: { title: string; text: string; confirmLabel: string; resolve: (confirmed: boolean) => void; } | null;
  setAppConfirm: React.Dispatch<React.SetStateAction<{ title: string; text: string; confirmLabel: string; resolve: (confirmed: boolean) => void; } | null>>;
  appPrompt: { title: string; value: string; multiline?: boolean | undefined; resolve: (text: string | null) => void; } | null;
  setAppPrompt: React.Dispatch<React.SetStateAction<{ title: string; value: string; multiline?: boolean | undefined; resolve: (text: string | null) => void; } | null>>;
  memoryPreview: any;
  setMemoryPreview: React.Dispatch<any>;
  searchPreview: import("../../../components/IndexLibrary.tsx").SearchPreviewTarget | null;
  setSearchPreview: React.Dispatch<React.SetStateAction<import("../../../components/IndexLibrary.tsx").SearchPreviewTarget | null>>;
  memoryCenterOpen: boolean;
  setMemoryCenterOpen: React.Dispatch<React.SetStateAction<boolean>>;
  memoryCenterTab: "library" | "search" | "layers" | "storage";
  setMemoryCenterTab: React.Dispatch<React.SetStateAction<"library" | "search" | "layers" | "storage">>;
  memoryProjectWorkspace: string;
  setMemoryProjectWorkspace: React.Dispatch<React.SetStateAction<string>>;
  memoryProjectEnabled: boolean;
  setMemoryProjectEnabled: React.Dispatch<React.SetStateAction<boolean>>;
  memoryProjectMenuOpen: boolean;
  setMemoryProjectMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  memoryProjectPickerRef: React.RefObject<HTMLDivElement | null>;
  openAppPrompt: (title: string, defaultValue?: string, multiline?: boolean) => Promise<string | null>;
  openAppConfirm: (title: string, text: string, confirmLabel?: string) => Promise<boolean>;
  expertTeams: ExpertTeamConfig[];
  setExpertTeams: React.Dispatch<React.SetStateAction<ExpertTeamConfig[]>>;
  expertTeamDraft: ExpertTeamConfig | null;
  setExpertTeamDraft: React.Dispatch<React.SetStateAction<ExpertTeamConfig | null>>;
  expertTeamEditorOpen: boolean;
  setExpertTeamEditorOpen: React.Dispatch<React.SetStateAction<boolean>>;
  expertTeamRunning: string | null;
  setExpertTeamRunning: React.Dispatch<React.SetStateAction<string | null>>;
  expertTeamMemberRunning: { teamId: string; memberName: string; } | null;
  setExpertTeamMemberRunning: React.Dispatch<React.SetStateAction<{ teamId: string; memberName: string; } | null>>;
  teamRuns: Record<string, TeamMemberRunRecord>;
  setTeamRuns: React.Dispatch<React.SetStateAction<Record<string, TeamMemberRunRecord>>>;
  teamPopupRunId: string;
  setTeamPopupRunId: React.Dispatch<React.SetStateAction<string>>;
  teamHistoryMember: string;
  setTeamHistoryMember: React.Dispatch<React.SetStateAction<string>>;
  threadTeamId: string;
  setThreadTeamId: React.Dispatch<React.SetStateAction<string>>;
  teamHistoryRuns: TeamMemberRunRecord[];
  setTeamHistoryRuns: React.Dispatch<React.SetStateAction<TeamMemberRunRecord[]>>;
  teamRunsRef: React.RefObject<Record<string, TeamMemberRunRecord>>;
  teamDeltaRef: React.RefObject<Map<string, string>>;
  teamFlushRef: React.RefObject<number | null>;
  teamRunningCountRef: React.RefObject<number>;
  teamCwdMap: Record<string, string>;
  setTeamCwdMap: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  expertTeamMemberDirect: string | null;
  setExpertTeamMemberDirect: React.Dispatch<React.SetStateAction<string | null>>;
  teamThreadMapRef: React.RefObject<Map<string, string>>;
  teamThreadConfigRef: React.RefObject<Map<string, { teamId: string; cwd: string; model: string; effort?: string | undefined; sandbox: string; approvalPolicy: string; }>>;
  pendingExpertRoleRef: React.RefObject<Map<string, ExpertPendingRole>>;
  EXPERT_ROLE_STORE_KEY: "expert-pending-roles";
  rememberExpertRole: (threadId: string, role: ExpertPendingRole) => void;
  forgetExpertRole: (threadId: string) => void;
  readStoredExpertRole: (threadId: string) => ExpertPendingRole | undefined;
  pendingImportThreads: Record<string, true>;
  setPendingImportThreads: React.Dispatch<React.SetStateAction<Record<string, true>>>;
  rememberPendingImport: (threadId: string, payload: PendingImportPayload) => void;
  forgetPendingImport: (threadId: string) => void;
  readStoredPendingImport: (threadId: string) => PendingImportPayload | undefined;
  panelWidth: number;
  setPanelWidth: React.Dispatch<React.SetStateAction<number>>;
  dragWidthRef: React.RefObject<number>;
  shellRef: React.RefObject<HTMLDivElement | null>;
  startPanelDrag: (event: React.MouseEvent<Element, MouseEvent>) => void;
  planSteps: { step: string; status: string; }[];
  setPlanSteps: React.Dispatch<React.SetStateAction<{ step: string; status: string; }[]>>;
  goalText: string;
  setGoalText: React.Dispatch<React.SetStateAction<string>>;
  goalsOpen: boolean;
  setGoalsOpen: React.Dispatch<React.SetStateAction<boolean>>;
  doneExpanded: boolean;
  setDoneExpanded: React.Dispatch<React.SetStateAction<boolean>>;
  planOnceRef: React.RefObject<boolean>;
  planTurnRef: React.RefObject<{ threadId: string; turnId: string; } | null>;
  planArmed: boolean;
  setPlanArmed: React.Dispatch<React.SetStateAction<boolean>>;
  planRunning: boolean;
  setPlanRunning: React.Dispatch<React.SetStateAction<boolean>>;
  planConfirm: { threadId: string; text: string; } | null;
  setPlanConfirm: React.Dispatch<React.SetStateAction<{ threadId: string; text: string; } | null>>;
  planFeedback: string;
  setPlanFeedback: React.Dispatch<React.SetStateAction<string>>;
  goalStatus: string | null;
  setGoalStatus: React.Dispatch<React.SetStateAction<string | null>>;
  goalsAutoGone: boolean;
  setGoalsAutoGone: React.Dispatch<React.SetStateAction<boolean>>;
  goalsPrevRunningRef: React.RefObject<boolean>;
  goalsTaskRunning: boolean;
  reviewBusy: boolean;
  setReviewBusy: React.Dispatch<React.SetStateAction<boolean>>;
  reviewReport: string;
  setReviewReport: React.Dispatch<React.SetStateAction<string>>;
  reviewTurnRef: React.RefObject<string | null>;
  treePath: string;
  setTreePath: React.Dispatch<React.SetStateAction<string>>;
  treeEntries: import("../../app-view/types.ts").TreeEntry[];
  setTreeEntries: React.Dispatch<React.SetStateAction<import("../../app-view/types.ts").TreeEntry[]>>;
  treeChildren: Record<string, import("../../app-view/types.ts").TreeEntry[]>;
  setTreeChildren: React.Dispatch<React.SetStateAction<Record<string, import("../../app-view/types.ts").TreeEntry[]>>>;
  treeExpanded: Set<string>;
  setTreeExpanded: React.Dispatch<React.SetStateAction<Set<string>>>;
  treeLoading: boolean;
  setTreeLoading: React.Dispatch<React.SetStateAction<boolean>>;
  browserHome: string;
  setBrowserHome: React.Dispatch<React.SetStateAction<string>>;
  browserUrl: string;
  setBrowserUrl: React.Dispatch<React.SetStateAction<string>>;
  browserDraft: string;
  setBrowserDraft: React.Dispatch<React.SetStateAction<string>>;
  browserMode: "cloak" | "internal";
  cloakPage: string;
  setCloakPage: React.Dispatch<React.SetStateAction<string>>;
  cloakStatus: string;
  setCloakStatus: React.Dispatch<React.SetStateAction<string>>;
  browserBookmarks: { url: string; title: string; }[];
  setBrowserBookmarks: React.Dispatch<React.SetStateAction<{ url: string; title: string; }[]>>;
  browserHistory: { url: string; title: string; at: number; }[];
  setBrowserHistory: React.Dispatch<React.SetStateAction<{ url: string; title: string; at: number; }[]>>;
  browserDrawer: "" | "bookmarks" | "history";
  setBrowserDrawer: React.Dispatch<React.SetStateAction<"" | "bookmarks" | "history">>;
  browserMenuOpen: boolean;
  setBrowserMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  backupBusy: "" | "export" | "import" | "export-md" | "import-md";
  setBackupBusy: React.Dispatch<React.SetStateAction<"" | "export" | "import" | "export-md" | "import-md">>;
  homeSites: { name: string; url: string; color?: string | undefined; }[];
  iframeRef: React.RefObject<HTMLIFrameElement | null>;
  queue: import("../../../lib/queue-item.ts").QueueItem[];
  setQueue: React.Dispatch<React.SetStateAction<import("../../../lib/queue-item.ts").QueueItem[]>>;
  queueDragIndex: number | null;
  setQueueDragIndex: React.Dispatch<React.SetStateAction<number | null>>;
  mobileNav: boolean;
  setMobileNav: React.Dispatch<React.SetStateAction<boolean>>;
  sidebarFlyout: boolean;
  setSidebarFlyout: React.Dispatch<React.SetStateAction<boolean>>;
  threadRowMenu: { id: string; top: number; right: number; } | null;
  setThreadRowMenu: React.Dispatch<React.SetStateAction<{ id: string; top: number; right: number; } | null>>;
  collapsedSections: Set<string>;
  setCollapsedSections: React.Dispatch<React.SetStateAction<Set<string>>>;
  toggleSection: (key: string) => void;
  threadAttention: Map<string, string>;
  renderThreadRow: (entry: import("../../app-view/types.ts").Thread, variant?: "member" | "lead" | undefined, extras?: { actions?: any; badge?: any; } | undefined) => React.JSX.Element;
  clusterSplit: (entries: import("../../app-view/types.ts").Thread[]) => { clusters: { teamId: string; lead: import("../../app-view/types.ts").Thread | null; members: import("../../app-view/types.ts").Thread[]; }[]; singles: import("../../app-view/types.ts").Thread[]; };
  renderClusterRow: (cluster: { teamId: string; lead: import("../../app-view/types.ts").Thread | null; members: import("../../app-view/types.ts").Thread[]; }) => React.JSX.Element | null;
  renderClusterList: (entries: import("../../app-view/types.ts").Thread[]) => React.JSX.Element;
  narrow: boolean;
  setNarrow: React.Dispatch<React.SetStateAction<boolean>>;
  approvalPolicy: string;
  setApprovalPolicy: React.Dispatch<React.SetStateAction<string>>;
  sandbox: string;
  setSandbox: React.Dispatch<React.SetStateAction<string>>;
  personality: string;
  setPersonality: React.Dispatch<React.SetStateAction<string>>;
  notices: { id: number; text: string; threadId?: string | undefined; scope: "settings" | "chat"; }[];
  setNotices: React.Dispatch<React.SetStateAction<{ id: number; text: string; threadId?: string | undefined; scope: "settings" | "chat"; }[]>>;
  noticeCenter: { id: number; text: string; threadId?: string | undefined; scope: "settings" | "chat"; at: number; read: boolean; }[];
  setNoticeCenter: React.Dispatch<React.SetStateAction<{ id: number; text: string; threadId?: string | undefined; scope: "settings" | "chat"; at: number; read: boolean; }[]>>;
  noticeCenterOpen: boolean;
  setNoticeCenterOpen: React.Dispatch<React.SetStateAction<boolean>>;
  noticeCenterBtnRef: React.RefObject<HTMLButtonElement | null>;
  historySearchBtnRef: React.RefObject<HTMLButtonElement | null>;
  closeHistoryPanel: () => void;
  jumpToHit: (hit: { turnId: string; itemId: string; text: string; }) => void;
  noticeChecked: Set<number>;
  setNoticeChecked: React.Dispatch<React.SetStateAction<Set<number>>>;
  noticeCenterUnread: number;
  noticeSeqRef: React.RefObject<number>;
  noticeTimersRef: React.RefObject<Map<number, number>>;
  settingsOpenRef: React.RefObject<boolean>;
  noticeAnchorTick: number;
  setNoticeAnchorTick: React.Dispatch<React.SetStateAction<number>>;
  dismissNotice: (id: number) => void;
  setNotice: (text: string, threadId?: string | undefined) => void;
  compactToast: { state: "error" | "running" | "success"; message?: string | undefined; threadId: string; } | null;
  setCompactToast: React.Dispatch<React.SetStateAction<{ state: "error" | "running" | "success"; message?: string | undefined; threadId: string; } | null>>;
  infoModal: { title: string; body: string; markdown?: boolean | undefined; } | null;
  setInfoModal: React.Dispatch<React.SetStateAction<{ title: string; body: string; markdown?: boolean | undefined; } | null>>;
  highlightedFilePath: string | null;
  setHighlightedFilePath: React.Dispatch<React.SetStateAction<string | null>>;
  /** 构建指纹（`YYYYMMDD-HHmm`，构建期注入；见 vite.config.ts 的 define）—— 回答"什么时候构建的" */
  buildStamp: string;
  /** 正在执行的渲染层 bundle 文件名（含内容 hash）—— 回答"跑的是哪一份文件" */
  bundleFile: string;
  lightbox: { path: string; alt: string; } | null;
  setLightbox: React.Dispatch<React.SetStateAction<{ path: string; alt: string; } | null>>;
  pastedText: { path: string; name: string; kind?: "file" | undefined; } | null;
  setPastedText: React.Dispatch<React.SetStateAction<{ path: string; name: string; kind?: "file" | undefined; } | null>>;
  systemEvents: import("../../app-view/types.ts").SystemEvent[];
  setSystemEvents: React.Dispatch<React.SetStateAction<import("../../app-view/types.ts").SystemEvent[]>>;
  hookPulse: { count: number; hooks: { name: string; label?: string | undefined; done: boolean; }[]; at: number; };
  setHookPulse: React.Dispatch<React.SetStateAction<{ count: number; hooks: { name: string; label?: string | undefined; done: boolean; }[]; at: number; }>>;
  welcomeScratchDir: string | null;
  setWelcomeScratchDir: React.Dispatch<React.SetStateAction<string | null>>;
  welcomeCwdMenuOpen: boolean;
  setWelcomeCwdMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  identityGreeted: boolean | null;
  setIdentityGreeted: React.Dispatch<React.SetStateAction<boolean | null>>;
  ponytailOn: boolean;
  setPonytailOn: React.Dispatch<React.SetStateAction<boolean>>;
  channelOnline: Record<string, boolean | undefined>;
  setChannelOnline: React.Dispatch<React.SetStateAction<Record<string, boolean | undefined>>>;
  switchJumpRef: React.RefObject<{ id: string; at: number; } | null>;
  switchJumpPending: () => boolean;
  threadCacheRef: React.RefObject<Map<string, import("../../app-view/types.ts").Thread>>;
  threadProviderRef: React.RefObject<Map<string, string>>;
  autoMigratedRef: React.RefObject<Set<string>>;
  switchingThreadId: string | null;
  setSwitchingThreadId: React.Dispatch<React.SetStateAction<string | null>>;
  switchSeqRef: React.RefObject<number>;
  recentResumeAtRef: React.RefObject<Map<string, number>>;
  turnsCursorRef: React.RefObject<Map<string, string | null>>;
  switchingFading: boolean;
  setSwitchingFading: React.Dispatch<React.SetStateAction<boolean>>;
  fadeOutTimerRef: React.RefObject<number | null>;
  switchHardTimerRef: React.RefObject<number | null>;
  theme: string;
  setTheme: React.Dispatch<React.SetStateAction<string>>;
  accountMenuOpen: boolean;
  setAccountMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  accountMenuSub: "theme" | "lang" | "zoom" | "update" | null;
  setAccountMenuSub: React.Dispatch<React.SetStateAction<"theme" | "lang" | "zoom" | "update" | null>>;
  updateInfo: { hasUpdate: boolean; version?: string | undefined; filename?: string | undefined; size?: number | undefined; sha256?: string | undefined; changelog?: string | undefined; mandatory?: boolean | undefined; downloadUrl?: string | undefined; reason?: string | undefined; } | null;
  setUpdateInfo: React.Dispatch<React.SetStateAction<{ hasUpdate: boolean; version?: string | undefined; filename?: string | undefined; size?: number | undefined; sha256?: string | undefined; changelog?: string | undefined; mandatory?: boolean | undefined; downloadUrl?: string | undefined; reason?: string | undefined; } | null>>;
  updateCurrentVersion: string;
  setUpdateCurrentVersion: React.Dispatch<React.SetStateAction<string>>;
  updateChecking: boolean;
  setUpdateChecking: React.Dispatch<React.SetStateAction<boolean>>;
  updateError: string;
  setUpdateError: React.Dispatch<React.SetStateAction<string>>;
  updateDownloading: boolean;
  setUpdateDownloading: React.Dispatch<React.SetStateAction<boolean>>;
  updateProgress: number;
  setUpdateProgress: React.Dispatch<React.SetStateAction<number>>;
  updateNotice: { version?: string | undefined; changelog?: string | undefined; size?: number | undefined; mandatory?: boolean | undefined; } | null;
  setUpdateNotice: React.Dispatch<React.SetStateAction<{ version?: string | undefined; changelog?: string | undefined; size?: number | undefined; mandatory?: boolean | undefined; } | null>>;
  accountMenuRef: React.RefObject<HTMLDivElement | null>;
  runUpdateCheck: () => Promise<void>;
  runUpdateDownload: () => Promise<void>;
  openFeedbackPage: () => void;
  uiLang: string;
  setUiLang: React.Dispatch<React.SetStateAction<string>>;
  uiZoom: number;
  setUiZoom: React.Dispatch<React.SetStateAction<number>>;
  uiFont: string;
  setUiFont: React.Dispatch<React.SetStateAction<string>>;
  settingsOpen: boolean;
  setSettingsOpen: React.Dispatch<React.SetStateAction<boolean>>;
  companyPreviewTeamId: string | null;
  setCompanyPreviewTeamId: React.Dispatch<React.SetStateAction<string | null>>;
  pptokenCardOff: boolean;
  setPptokenCardOff: React.Dispatch<React.SetStateAction<boolean>>;
  settingsPage: import("../../app-view/types.ts").SettingsPage;
  setSettingsPage: React.Dispatch<React.SetStateAction<import("../../app-view/types.ts").SettingsPage>>;
  shortcutsOpen: boolean;
  setShortcutsOpen: React.Dispatch<React.SetStateAction<boolean>>;
  helpKey: import("../../../components/HelpDialog.tsx").HelpTopic | null;
  setHelpKey: React.Dispatch<React.SetStateAction<import("../../../components/HelpDialog.tsx").HelpTopic | null>>;
  archiveToast: { name: string; token: number; } | null;
  setArchiveToast: React.Dispatch<React.SetStateAction<{ name: string; token: number; } | null>>;
  showModelGuide: boolean;
  setShowModelGuide: React.Dispatch<React.SetStateAction<boolean>>;
  quickSetupBusy: boolean;
  setQuickSetupBusy: React.Dispatch<React.SetStateAction<boolean>>;
  quickSetupError: string;
  setQuickSetupError: React.Dispatch<React.SetStateAction<string>>;
  relaySetupBusy: boolean;
  setRelaySetupBusy: React.Dispatch<React.SetStateAction<boolean>>;
  relaySetupError: string;
  setRelaySetupError: React.Dispatch<React.SetStateAction<string>>;
  modelGuideDoneRef: React.RefObject<boolean>;
  envCheckOpen: boolean;
  setEnvCheckOpen: React.Dispatch<React.SetStateAction<boolean>>;
  envInstalling: boolean;
  setEnvInstalling: React.Dispatch<React.SetStateAction<boolean>>;
  envCheckDoneRef: React.RefObject<boolean>;
  codexIdentity: import("../../../lib/codex-identity.mjs").CodexIdentity;
  toolsStatus: { id: string; name: string; scope: "browser" | "computer"; version: string; installed: boolean; binaryReady: boolean; detail: string; command: string; }[];
  setToolsStatus: React.Dispatch<React.SetStateAction<{ id: string; name: string; scope: "browser" | "computer"; version: string; installed: boolean; binaryReady: boolean; detail: string; command: string; }[]>>;
  refreshToolsStatus: () => void;
  devRuntimes: DevRuntimeEntry[];
  setDevRuntimes: React.Dispatch<React.SetStateAction<DevRuntimeEntry[]>>;
  runtimeInstalling: string | null;
  setRuntimeInstalling: React.Dispatch<React.SetStateAction<string | null>>;
  runtimeProgress: Record<string, string>;
  setRuntimeProgress: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  runtimePercent: Record<string, number>;
  setRuntimePercent: React.Dispatch<React.SetStateAction<Record<string, number>>>;
  runtimeStage: Record<string, string>;
  setRuntimeStage: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  runtimeSpeed: Record<string, string>;
  setRuntimeSpeed: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  runtimeActiveId: string;
  setRuntimeActiveId: React.Dispatch<React.SetStateAction<string>>;
  runtimeModal: { id: string; name: string; mode: "install" | "uninstall"; done: boolean; failed: boolean; } | null;
  setRuntimeModal: React.Dispatch<React.SetStateAction<{ id: string; name: string; mode: "install" | "uninstall"; done: boolean; failed: boolean; } | null>>;
  refreshDevRuntimes: () => void;
  capabilityRows: { id: string; label: string; purpose: string; activeId: string | null; activeLabel: string; activeWhy: string; alternatives: { id: string; label: string; available: boolean; }[]; note: string; }[];
  setCapabilityRows: React.Dispatch<React.SetStateAction<{ id: string; label: string; purpose: string; activeId: string | null; activeLabel: string; activeWhy: string; alternatives: { id: string; label: string; available: boolean; }[]; note: string; }[]>>;
  capabilityError: string;
  setCapabilityError: React.Dispatch<React.SetStateAction<string>>;
  refreshCapabilities: () => void;
  installDevRuntime: (id: string) => Promise<void>;
  uninstallDevRuntime: (id: string) => Promise<void>;
  settingsResources: { skills: any[]; hooks: any[]; plugins: any[]; mcp: any[]; };
  setSettingsResources: React.Dispatch<React.SetStateAction<{ skills: any[]; hooks: any[]; plugins: any[]; mcp: any[]; }>>;
  installedTotalCount: number;
  resourceLoading: boolean;
  setResourceLoading: React.Dispatch<React.SetStateAction<boolean>>;
  resourceError: string;
  setResourceError: React.Dispatch<React.SetStateAction<string>>;
  pluginSearch: string;
  setPluginSearch: React.Dispatch<React.SetStateAction<string>>;
  pluginInstalledOnly: boolean;
  setPluginInstalledOnly: React.Dispatch<React.SetStateAction<boolean>>;
  pluginBusy: string | null;
  setPluginBusy: React.Dispatch<React.SetStateAction<string | null>>;
  pluginBatchBusy: "enable" | "disable" | null;
  setPluginBatchBusy: React.Dispatch<React.SetStateAction<"enable" | "disable" | null>>;
  skillBatchBusy: "enable" | "disable" | null;
  setSkillBatchBusy: React.Dispatch<React.SetStateAction<"enable" | "disable" | null>>;
  pluginChecked: string[];
  setPluginChecked: React.Dispatch<React.SetStateAction<string[]>>;
  skillChecked: string[];
  setSkillChecked: React.Dispatch<React.SetStateAction<string[]>>;
  skillManageSearch: string;
  setSkillManageSearch: React.Dispatch<React.SetStateAction<string>>;
  customCommands: CustomCommandEntry[];
  setCustomCommands: React.Dispatch<React.SetStateAction<CustomCommandEntry[]>>;
  commandSearch: string;
  setCommandSearch: React.Dispatch<React.SetStateAction<string>>;
  commandFilter: "all" | "custom" | "builtin" | "skill";
  setCommandFilter: React.Dispatch<React.SetStateAction<"all" | "custom" | "builtin" | "skill">>;
  commandBusy: boolean;
  setCommandBusy: React.Dispatch<React.SetStateAction<boolean>>;
  commandEditor: { mode: "new" | "edit"; name: string; source: CommandSource; description: string; argumentHint: string; allowedTools: string; model: string; body: string; prevFilePath?: string | undefined; } | null;
  setCommandEditor: React.Dispatch<React.SetStateAction<{ mode: "new" | "edit"; name: string; source: CommandSource; description: string; argumentHint: string; allowedTools: string; model: string; body: string; prevFilePath?: string | undefined; } | null>>;
  commandDelete: CustomCommandEntry | null;
  setCommandDelete: React.Dispatch<React.SetStateAction<CustomCommandEntry | null>>;
  commandBusyKey: string | null;
  setCommandBusyKey: React.Dispatch<React.SetStateAction<string | null>>;
  refreshCommands: () => Promise<void>;
  persistCommand: () => Promise<void>;
  confirmDeleteCommand: () => Promise<void>;
  useCommand: (name: string, kind: "custom" | "builtin" | "skill", skill?: any) => void;
  hookTrusting: boolean;
  setHookTrusting: React.Dispatch<React.SetStateAction<boolean>>;
  hookBusy: string | null;
  setHookBusy: React.Dispatch<React.SetStateAction<string | null>>;
  linkedBusy: string | null;
  setLinkedBusy: React.Dispatch<React.SetStateAction<string | null>>;
  projectFilter: string | null;
  setProjectFilter: React.Dispatch<React.SetStateAction<string | null>>;
  username: string;
  setUsername: React.Dispatch<React.SetStateAction<string>>;
  userAvatar: import("../../../lib/user-identity.mjs").UserAvatarSpec | null;
  setUserAvatar: React.Dispatch<React.SetStateAction<import("../../../lib/user-identity.mjs").UserAvatarSpec | null>>;
  accountEditing: boolean;
  setAccountEditing: React.Dispatch<React.SetStateAction<boolean>>;
  accountDraft: string;
  setAccountDraft: React.Dispatch<React.SetStateAction<string>>;
  accountNameRef: React.RefObject<HTMLInputElement | null>;
  saveAccountName: () => void;
  startAccountEdit: () => void;
  greeting: string;
  greetSub: string;
  mobileRemoteOpen: boolean;
  setMobileRemoteOpen: React.Dispatch<React.SetStateAction<boolean>>;
  botManagerOpen: boolean;
  setBotManagerOpen: React.Dispatch<React.SetStateAction<boolean>>;
  botManagerOpenRef: React.RefObject<boolean>;
  botStream: { enabled: boolean; thinking: boolean; tools: boolean; };
  setBotStream: React.Dispatch<React.SetStateAction<{ enabled: boolean; thinking: boolean; tools: boolean; }>>;
  updateBotStream: (next: { enabled: boolean; thinking: boolean; tools: boolean; }) => void;
  botBindings: { wechat: { threadId: string; title: string; updatedAt: number; } | null; telegram: { threadId: string; title: string; updatedAt: number; } | null; };
  setBotBindings: React.Dispatch<React.SetStateAction<{ wechat: { threadId: string; title: string; updatedAt: number; } | null; telegram: { threadId: string; title: string; updatedAt: number; } | null; }>>;
  setBotBinding: (channel: "telegram" | "wechat", threadId: string | null, title?: string | undefined) => Promise<void>;
  bots: BotEntry[];
  setBots: React.Dispatch<React.SetStateAction<BotEntry[]>>;
  activeBotId: string | null;
  setActiveBotId: React.Dispatch<React.SetStateAction<string | null>>;
  setBotsPersist: (updater: BotEntry[] | ((cur: BotEntry[]) => BotEntry[])) => void;
  botChannelPick: string | null;
  setBotChannelPick: React.Dispatch<React.SetStateAction<string | null>>;
  botQr: string;
  setBotQr: React.Dispatch<React.SetStateAction<string>>;
  remoteUrl: string;
  setRemoteUrl: React.Dispatch<React.SetStateAction<string>>;
  remoteDevices: any[];
  setRemoteDevices: React.Dispatch<React.SetStateAction<any[]>>;
  remoteStatus: string;
  setRemoteStatus: React.Dispatch<React.SetStateAction<string>>;
  remoteCmd: string;
  setRemoteCmd: React.Dispatch<React.SetStateAction<string>>;
  remoteLog: string[];
  setRemoteLog: React.Dispatch<React.SetStateAction<string[]>>;
  remoteQr: string;
  setRemoteQr: React.Dispatch<React.SetStateAction<string>>;
  pairCode: string;
  setPairCode: React.Dispatch<React.SetStateAction<string>>;
  pairPending: any[];
  setPairPending: React.Dispatch<React.SetStateAction<any[]>>;
  pairApproved: any[];
  setPairApproved: React.Dispatch<React.SetStateAction<any[]>>;
  loadPairStates: () => Promise<void>;
  userDataPath: string;
  setUserDataPath: React.Dispatch<React.SetStateAction<string>>;
  taskMenuOpen: boolean;
  setTaskMenuOpen: React.Dispatch<React.SetStateAction<boolean>>;
  renameDraft: string;
  setRenameDraft: React.Dispatch<React.SetStateAction<string>>;
  inlineRename: boolean;
  setInlineRename: React.Dispatch<React.SetStateAction<boolean>>;
  inlineRenameRef: React.RefObject<HTMLInputElement | null>;
  interruptedTurns: Record<string, number>;
  setInterruptedTurns: React.Dispatch<React.SetStateAction<Record<string, number>>>;
  stoppedElapsed: Record<string, number>;
  setStoppedElapsed: React.Dispatch<React.SetStateAction<Record<string, number>>>;
  closeTaskMenu: () => void;
  awayFromBottom: boolean;
  setAwayFromBottom: React.Dispatch<React.SetStateAction<boolean>>;
  stickToBottomRef: React.RefObject<boolean>;
  anchorTopRef: React.RefObject<boolean>;
  dbg: (r: string, extra?: any) => void;
  selfScrollUntilRef: React.RefObject<number>;
  anchorElRef: React.RefObject<HTMLElement | null>;
  anchorTurnIdRef: React.RefObject<string | null>;
  contentAnchorTopRef: React.RefObject<number>;
  anchorTopOffsetRef: React.RefObject<number>;
  anchorHeightBaselineRef: React.RefObject<number>;
  anchorSpacerRef: React.RefObject<HTMLDivElement | null>;
  anchorPadAppliedRef: React.RefObject<number | null>;
  clearAnchorPad: () => void;
  compactSpacerRef: React.RefObject<HTMLDivElement | null>;
  contentBottomOf: (el: HTMLElement) => number;
  bodyBottomOf: (el: HTMLElement) => number;
  contentTailTarget: (el: HTMLElement) => number;
  pinSentMessage: (el: HTMLElement, threadId?: string | null | undefined) => boolean;
  pinnedScrollTopRef: React.RefObject<number>;
  pinGapLockedRef: React.RefObject<string | null>;
  pinThreadIdRef: React.RefObject<string | null>;
  pinDormantSeenRef: React.RefObject<boolean>;
  pinFixRef: React.RefObject<number>;
  pinnedAnchorKeyRef: React.RefObject<string | null>;
  anchorGlideRef: React.RefObject<number>;
  glideTo: (el: HTMLElement, target: number) => void;
  workStartedAt: number | null;
  setWorkStartedAt: React.Dispatch<React.SetStateAction<number | null>>;
  scrollRef: React.RefObject<HTMLDivElement | null>;
  timelineWrapRef: React.RefObject<HTMLDivElement | null>;
  searchRef: React.RefObject<HTMLInputElement | null>;
  composerInputRef: React.RefObject<HTMLDivElement | null>;
  composerWrapRef: React.RefObject<HTMLDivElement | null>;
  composerDomValueRef: React.RefObject<string | null>;
  makeComposerChip: (kind: "file" | "image", path: string) => HTMLElement;
  syncComposerFromDom: () => void;
  messageHandlersRef: React.RefObject<import("../../session-queue/SessionQueue.tsx").FoldHandlers | null>;
  messageHandlers: import("../../session-queue/SessionQueue.tsx").FoldHandlers;
  memoryEnabled: boolean;
  memories: import("../../../hooks/useMemory.ts").MemoryRecord[];
  setMemories: React.Dispatch<React.SetStateAction<import("../../../hooks/useMemory.ts").MemoryRecord[]>>;
  memoryCategory: string;
  setMemoryCategory: React.Dispatch<React.SetStateAction<string>>;
  memorySaveCategory: string;
  setMemorySaveCategory: React.Dispatch<React.SetStateAction<string>>;
  memorySavedAt: number | null;
  memoryDraft: string;
  setMemoryDraft: React.Dispatch<React.SetStateAction<string>>;
  memoryStatus: string;
  setMemoryStatus: React.Dispatch<React.SetStateAction<string>>;
  memoryGateway: import("../../../hooks/useMemory.ts").MemoryGatewayState;
  setMemoryGateway: React.Dispatch<React.SetStateAction<import("../../../hooks/useMemory.ts").MemoryGatewayState>>;
  memoryGatewayAction: "save" | "test" | null;
  memoryMode: import("../../../hooks/useMemory.ts").MemoryMode;
  updateMemoryMode: (mode: import("../../../hooks/useMemory.ts").MemoryMode) => Promise<void>;
  workspaceMemoryEnabled: boolean;
  updateWorkspaceMemory: (enabled: boolean, workspaceOverride?: string | undefined) => void;
  saveMemoryRecord: (workspaceOverride?: string | undefined) => Promise<void>;
  deleteMemoryRecord: (id: string) => Promise<void>;
  deleteMemoryGroup: (predicate: (entry: import("../../../hooks/useMemory.ts").MemoryRecord) => boolean) => Promise<number>;
  resetMemory: () => Promise<void>;
  testMemoryGateway: () => Promise<void>;
  saveMemoryGateway: () => Promise<void>;
  setMemoryEnabled: (enabled: boolean) => Promise<void>;
  memoryProjectOptions: string[];
  memoryManagementWorkspace: string;
  memoryEntryBelongsToProject: (entry: import("../../../hooks/useMemory.ts").MemoryRecord, project: string) => boolean;
  memoryVisibleRecords: import("../../../hooks/useMemory.ts").MemoryRecord[];
  memoryTitleById: (id: string) => string | undefined;
  memoryGroups: import("../../../hooks/useMemory.ts").MemoryGroup[];
  memoryGroupsFiltered: import("../../../hooks/useMemory.ts").MemoryGroup[];
  memoryLayers: MemoryLayersSnapshot | null;
  setMemoryLayers: React.Dispatch<React.SetStateAction<MemoryLayersSnapshot | null>>;
  memoryLayerScope: "user" | "project" | "background";
  setMemoryLayerScope: React.Dispatch<React.SetStateAction<"user" | "project" | "background">>;
  memoryLayerDraft: string;
  setMemoryLayerDraft: React.Dispatch<React.SetStateAction<string>>;
  memoryLayerSavedAt: number | null;
  setMemoryLayerSavedAt: React.Dispatch<React.SetStateAction<number | null>>;
  memoryDistilling: boolean;
  setMemoryDistilling: React.Dispatch<React.SetStateAction<boolean>>;
  applyMemoryLayers: (snapshot: MemoryLayersSnapshot, scope: "user" | "project" | "background") => void;
  memoryLayerDirty: boolean;
  saveMemoryLayer: () => Promise<void>;
  runMemoryDistill: () => Promise<void>;
  togglePinned: (id: string) => Promise<void>;
  clearSelectedMemory: () => Promise<void>;
  scheduledTasks: import("../../../hooks/useScheduler.ts").ScheduledTask[];
  setScheduledTasks: React.Dispatch<React.SetStateAction<import("../../../hooks/useScheduler.ts").ScheduledTask[]>>;
  scheduleDraft: import("../../../hooks/useScheduler.ts").ScheduleDraft;
  setScheduleDraft: React.Dispatch<React.SetStateAction<import("../../../hooks/useScheduler.ts").ScheduleDraft>>;
  autoFormVisible: boolean;
  setAutoFormVisible: React.Dispatch<React.SetStateAction<boolean>>;
  scheduleStatus: string;
  saveSchedule: () => Promise<boolean>;
  toggleSchedule: (task: import("../../../hooks/useScheduler.ts").ScheduledTask) => Promise<void>;
  deleteSchedule: (id: string) => Promise<void>;
  runSchedule: (id: string) => Promise<void>;
  editSchedule: (id: string) => void;
  channelBot: import("../../../hooks/useChannelBot.ts").ChannelBot | null;
  setChannelBot: React.Dispatch<React.SetStateAction<import("../../../hooks/useChannelBot.ts").ChannelBot | null>>;
  channelDraft: import("../../../hooks/useChannelBot.ts").ChannelDraft;
  setChannelDraft: React.Dispatch<React.SetStateAction<import("../../../hooks/useChannelBot.ts").ChannelDraft>>;
  channelAction: "save" | "test" | null;
  channelStatus: string;
  setChannelStatus: React.Dispatch<React.SetStateAction<string>>;
  saveChannelBot: () => Promise<void>;
  testChannelBot: () => Promise<void>;
  chooseChannelWorkspace: () => Promise<void>;
  customModel: import("../../../hooks/useModelProviders.ts").CustomModel | null;
  setCustomModel: React.Dispatch<React.SetStateAction<import("../../../hooks/useModelProviders.ts").CustomModel | null>>;
  customDraft: import("../../../hooks/useModelProviders.ts").ProviderDraft;
  setCustomDraft: React.Dispatch<React.SetStateAction<import("../../../hooks/useModelProviders.ts").ProviderDraft>>;
  providersList: import("../../../hooks/useModelProviders.ts").ProviderSummary[];
  currentProvider: string | null;
  editingProvider: string | null;
  setEditingProvider: React.Dispatch<React.SetStateAction<string | null>>;
  savingSettings: boolean;
  providerModels: string[];
  modelSourceProvider: string | null;
  refreshActive: () => void;
  probingProvider: "test" | "list" | null;
  providerStatus: string;
  switchingModel: string | null;
  saveCustomModel: () => Promise<any>;
  probeProvider: (mode: "test" | "list") => Promise<void>;
  probeActiveProvider: () => Promise<void>;
  selectProvider: (providerId: string) => Promise<void>;
  removeProvider: (provider: import("../../../hooks/useModelProviders.ts").ProviderSummary) => Promise<void>;
  setProviderModel: (providerId: string, model: string) => Promise<void>;
  removeProviderModel: (providerId: string, modelId: string) => Promise<void>;
  upsertProviderModel: (providerId: string, model: import("../../../hooks/useModelProviders.ts").ProviderModel) => Promise<void>;
  setProviderEnabled: (providerId: string, enabled: boolean) => Promise<void>;
  probeOneModel: (providerId: string, modelId: string) => Promise<void>;
  adoptSavedProvider: (saved: import("../../../hooks/useModelProviders.ts").CustomModel, probedModels?: string[]) => void;
  saveCustomDraft: (override?: any) => Promise<any>;
  activeProviderRef: React.RefObject<{ provider: string; model: string; name: string; baseUrl: string; wireApi?: string | undefined; } | null>;
  providerAutoOpenRef: React.RefObject<boolean>;
  pendingRestart: { provider: string; model: string; label: string; prevProvider: string; prevModel: string; } | null;
  setPendingRestart: React.Dispatch<React.SetStateAction<{ provider: string; model: string; label: string; prevProvider: string; prevModel: string; } | null>>;
  pendingRestartRef: React.RefObject<{ provider: string; model: string; label: string; prevProvider: string; prevModel: string; } | null>;
  relayActivate: (mode: "balance" | "plan", group?: { group_id: number; group_name: string; } | undefined, explicitKey?: { id: any; name: any; key: string; group_id: number | null; } | undefined, retried?: boolean) => Promise<void>;
  activateOfficialProvider: (modelsInput?: string[] | undefined) => Promise<void>;
  filePreview: import("../../../hooks/useFilePreview.ts").FilePreview | null;
  setFilePreview: React.Dispatch<React.SetStateAction<import("../../../hooks/useFilePreview.ts").FilePreview | null>>;
  fileTabs: string[];
  closeTab: (path: string) => void;
  fileEditing: boolean;
  setFileEditing: React.Dispatch<React.SetStateAction<boolean>>;
  fileDraft: string;
  setFileDraft: React.Dispatch<React.SetStateAction<string>>;
  savingFile: boolean;
  rawOpenFile: (path: string) => Promise<void>;
  saveFilePreview: () => Promise<void>;
  openFile: (path: string) => Promise<void>;
  customModelEfforts: string[];
  customModelOption: import("../../app-view/types.ts").Model | null;
  allModels: import("../../app-view/types.ts").Model[];
  archiveSyncRef: React.RefObject<string>;
  modelSuggestions: string[];
  modelEditor: { mode: "edit" | "add"; originalId: string | null; paramsDirty?: boolean | undefined; draft: { id: string; contextWindow: string; maxOutputTokens: string; inputTypes: ("image" | "text" | "video")[]; outputTypes: ("image" | "text" | "video")[]; }; } | null;
  setModelEditor: React.Dispatch<React.SetStateAction<{ mode: "edit" | "add"; originalId: string | null; paramsDirty?: boolean | undefined; draft: { id: string; contextWindow: string; maxOutputTokens: string; inputTypes: ("image" | "text" | "video")[]; outputTypes: ("image" | "text" | "video")[]; }; } | null>>;
  showApiKey: boolean;
  setShowApiKey: React.Dispatch<React.SetStateAction<boolean>>;
  applyModelIdInput: (id: string) => void;
  openModelEditor: (m?: { id: string; contextWindow?: number | undefined; maxOutputTokens?: number | undefined; inputTypes?: ("image" | "text" | "video")[] | undefined; outputTypes?: ("image" | "text" | "video")[] | undefined; } | undefined) => void;
  targetProviderHint: string | undefined;
  saveModelEditor: () => Promise<void>;
  selectedModel: import("../../app-view/types.ts").Model | undefined;
  currentModelId: string;
  usingCustomModel: boolean;
  providerConfig: { modelProvider: "harness"; config: { model_provider: "harness"; model_providers: { harness: { name: string; base_url: string; env_key: string; wire_api: "responses"; requires_openai_auth: boolean; }; }; }; } | { modelProvider?: undefined; config?: undefined; };
  listThreads: import("../../app-view/types.ts").Thread[];
  dispatchCwdMap: Record<string, string>;
  viewTab: "projects" | "source";
  setViewTab: React.Dispatch<React.SetStateAction<"projects" | "source">>;
  expandedProjects: Set<string>;
  setExpandedProjects: React.Dispatch<React.SetStateAction<Set<string>>>;
  toggleProjectExpanded: (cwd: string) => void;
  cwdOverrides: Record<string, string>;
  setCwdOverrides: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  cwdOverridesRef: React.RefObject<Record<string, string>>;
  rememberThreadCwd: (threadId: string | null | undefined, cwd: string) => void;
  effectiveCwd: (threadId: string | null | undefined, engineCwd: string | null | undefined) => string;
  withCwdOverride: <T extends { id: string; cwd: string; }>(entry: T) => T;
  nameOverrides: Record<string, string>;
  setNameOverrides: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  nameOverridesRef: React.RefObject<Record<string, string>>;
  rememberThreadName: (threadId: string | null | undefined, name: string) => void;
  effectiveThreadName: (threadId: string | null | undefined, engineName: string | null | undefined) => string;
  withNameOverride: <T extends { id: string; name?: string | null; }>(entry: T) => T;
  projectMenu: string | null;
  setProjectMenu: React.Dispatch<React.SetStateAction<string | null>>;
  pinnedThreads: string[];
  setPinnedThreads: React.Dispatch<React.SetStateAction<string[]>>;
  togglePinThread: (id: string) => void;
  projectGroups: [string, import("../../app-view/types.ts").Thread[]][];
  allProjectsCollapsed: boolean;
  toggleAllProjects: () => void;
  projectAutoExpandRef: React.RefObject<boolean>;
  sourcedThreads: { key: string; label: string; items: import("../../app-view/types.ts").Thread[]; }[];
  allSourceGroupsCollapsed: boolean;
  sourcedChildrenOf: Record<string, { threadId: string; kind: string; name: string; }[]>;
  sourcedDispatch: { childrenOf: Record<string, { threadId: string; kind: string; name: string; }[]>; childIds: Set<string>; };
  sourcedChildIds: Set<string>;
  teamThreadsIndex: Record<string, string>;
  setTeamThreadsIndex: React.Dispatch<React.SetStateAction<Record<string, string>>>;
  teamMemberThreadIds: Set<string>;
  setTeamMemberThreadIds: React.Dispatch<React.SetStateAction<Set<string>>>;
  expandedTeamClusters: Set<string>;
  expandedDispatchBlocks: Set<string>;
  setExpandedDispatchBlocks: React.Dispatch<React.SetStateAction<Set<string>>>;
  toggleDispatchBlock: (key: string) => void;
  dispatchBlockKeys: string[];
  setExpandedTeamClusters: React.Dispatch<React.SetStateAction<Set<string>>>;
  toggleTeamCluster: (teamId: string) => void;
  clusteredSidebar: { memberIds: Set<string>; clusters: { teamId: string; lead: import("../../app-view/types.ts").Thread | null; members: import("../../app-view/types.ts").Thread[]; }[]; };
  toggleAllSources: () => void;
  sidebarAllCollapsed: boolean;
  toggleAllSidebarSections: () => void;
  TURN_WINDOW: 5;
  TURNS_PAGE: 5;
  TURN_WINDOW_MEMORY_KEEP: 8;
  touchTurnWindow: (id: string, map: Record<string, number>) => Record<string, number>;
  ANCHOR_TOP_OFFSET_PX: 36;
  CONTENT_TAIL_GAP_PX: 0;
  COMMON_COMMAND_ORDER: string[];
  commandMatches: (readonly [string, string])[];
  mergedSkillCatalog: { name: string; description: string; note: string; path: string; }[];
  skillCommandMatches: { name: string; description: string; note: string; path: string; }[];
  threadMemoKey: string;
  availableContextItems: { id: string; role: "用户" | "Codex"; text: any; }[];
  threadFileCandidates: { path: string; source: string; }[];
  addSystemEvent: (title: string, text: string, tone?: "error" | "success" | "info" | "warning" | undefined) => void;
  setCompactEventState: (state: "error" | "running" | "success", detail?: string | undefined) => void;
  /** 压缩结束的运行态结算：清掉被压缩回合点亮的 sending/activeTurnId/running（真回合在跑时不动） */
  settleAfterCompaction: (threadId: string) => void;
  pruneSupersededCompactions: (keepId: string) => void;
  threadNameOf: (threadId: string) => string;
  scopedNotice: (text: string, threadId?: string | undefined) => void;
  showToast: (title: string, text?: unknown, threadId?: string | undefined) => void;
  contextUsageText: () => string;
  addHookEvent: (running: boolean, hookName: string) => void;
  pendingCommandTextRef: React.RefObject<string | null>;
  updateBottomStateRef: React.RefObject<() => void>;
  /** 上一次 update() 结束时记下的「内容底部 / 视口位置 / 当时是否贴底」：识别"内容变矮"（折叠）并跟随贴合。
   *  ⛔ 必须登记进 Bag —— 预检【93】要求 parts 里推断出的每个名字都在这里（漏登记 = 守卫红）。 */
  lastBottomRef: React.RefObject<{ cb: number; top: number; atBottom: boolean; } | null>;
  turnResizeObserverRef: React.RefObject<ResizeObserver | null>;
  releaseToUserRef: React.RefObject<(why: string) => void>;
  chatSearchOpen: boolean;
  setChatSearchOpen: React.Dispatch<React.SetStateAction<boolean>>;
  chatSearchQuery: string;
  setChatSearchQuery: React.Dispatch<React.SetStateAction<string>>;
  chatSearchIndex: number;
  setChatSearchIndex: React.Dispatch<React.SetStateAction<number>>;
  chatSearchHistoryOpen: boolean;
  setChatSearchHistoryOpen: React.Dispatch<React.SetStateAction<boolean>>;
  chatSearchHistory: string[];
  setChatSearchHistory: React.Dispatch<React.SetStateAction<string[]>>;
  chatSearchRef: React.RefObject<HTMLInputElement | null>;
  chatSearchHistoryRef: React.RefObject<HTMLDivElement | null>;
  chatSearchResults: { turnId: string; itemId: string; type: string; text: string; }[];
  chatSearchGo: (dir: 1 | -1) => void;
  pushChatSearchHistory: (query: string) => void;
  removeChatSearchHistory: (entry: string) => void;
  clearChatSearchHistory: () => void;
  knownFilesRef: React.RefObject<{ src: import("../../app-view/types.ts").Thread | null; map: Map<string, string>; }>;
  refreshThreads: () => Promise<void>;
  sidebarRefreshTimerRef: React.RefObject<number | null>;
  scheduleSidebarRefresh: () => void;
  refreshQueue: (threadId: string) => Promise<void>;
  /** 环境自查：把主进程 `app:doctor` 的体检结论落到信息弹窗并复制（09-23 接上 `/doctor`） */
  runEnvironmentCheck: () => Promise<void>;
  fetchChildren: (path: string) => Promise<void>;
  toggleTreeDir: (dir: string) => void;
  loadTree: (path: string) => Promise<void>;
  describeCloakEvent: (event: { event?: string | undefined; message?: string | undefined; url?: string | undefined; title?: string | undefined; }) => string;
  openInCloak: (url: string) => Promise<void>;
  openBrowser: () => void;
  toggleBookmark: () => void;
  deleteQueued: (id: string) => Promise<void>;
  reorderQueued: (from: number, to: number) => Promise<void>;
  editQueued: (entry: import("../../../lib/queue-item.ts").QueueItem) => void;
  saveQueued: (entry: import("../../../lib/queue-item.ts").QueueItem, text: string) => Promise<void>;
  armPinForReleasedQueue: (threadId: string | null | undefined, why: string) => boolean;
  disarmPinIntent: (why: string) => void;
  maybeAutoContinueTruncated: (threadId: string) => void;
  startQueued: (id?: string | undefined) => Promise<void>;
  refreshSettingsResources: (opts?: { mcpDetail?: boolean | undefined; }) => Promise<void>;
  trustAllHooks: () => Promise<void>;
  setHookEnabled: (hook: any, enabled: boolean) => Promise<void>;
  setLinkedEnabled: (pluginId: string, enabled: boolean, label: string) => Promise<void>;
  changePlugin: (plugin: any) => Promise<void>;
  setPluginEnabled: (plugin: any, enabled: boolean) => Promise<void>;
  ponytailPluginEntry: any;
  ponytailPluginOn: boolean;
  ponytailSkillsSnap: { folder: string; enabled: boolean; }[];
  desktopSkillSnap: import("../../../lib/capability-groups.ts").SkillMember | null;
  browserSkillsSnap: import("../../../lib/capability-groups.ts").SkillMember[];
  nuphusMcpOn: boolean;
  capabilitySnapshot: import("../../../lib/capability-groups.ts").SubToggleSnapshot;
  groupBusy: import("../../../lib/capability-groups.ts").CapabilityGroupId | null;
  setGroupBusy: React.Dispatch<React.SetStateAction<import("../../../lib/capability-groups.ts").CapabilityGroupId | null>>;
  groupIpc: import("../../../lib/capability-groups.ts").GroupIpc;
  applyGroup: (groupId: import("../../../lib/capability-groups.ts").CapabilityGroupId, target: boolean, silent?: boolean) => Promise<void>;
  bootHealRef: React.RefObject<boolean>;
  guardGroupOff: (member: { kind: "plugin"; id: string; } | { kind: "skill"; folder?: string | undefined; name?: string | undefined; pluginId?: string | undefined; } | { kind: "mcp"; name: string; }, label: string, next: boolean) => boolean;
  capabilityHint: (groupId: import("../../../lib/capability-groups.ts").CapabilityGroupId) => string | null;
  batchSetPluginEnabled: (plugins: any[], enabled: boolean) => Promise<void>;
  batchSetSkillEnabled: (folders: string[], enabled: boolean) => Promise<void>;
  popoutFromQuery: string | null;
  envSpecs: { id: string; why: string; core: boolean; go?: "model" | undefined; fallbackName: string; }[];
  envItems: import("../../../components/EnvCheckDialog.tsx").EnvCheckState[];
  installEnvMissing: (ids: string[]) => Promise<void>;
  envProgress: string;
  envPercent: number | undefined;
  envStage: string | undefined;
  envSpeed: string | undefined;
  healImageModalityIfUnsupported: (message: string | undefined) => Promise<void>;
  settingsContentReady: boolean;
  setSettingsContentReady: React.Dispatch<React.SetStateAction<boolean>>;
  mcpDetailLoadedRef: React.RefObject<boolean>;
  skillHubSearchDebounced: string;
  setSkillHubSearchDebounced: React.Dispatch<React.SetStateAction<string>>;
  pluginMarketSearchDebounced: string;
  setPluginMarketSearchDebounced: React.Dispatch<React.SetStateAction<string>>;
  lastStreamTsRef: React.RefObject<number>;
  baseInstructionsRef: React.RefObject<string>;
  scopeSigRef: React.RefObject<Record<string, string>>;
  adaptiveToneRef: React.RefObject<boolean>;
  moodKeyOf: (threadId: string) => string;
  readMood: (threadId: string) => import("../../../lib/agent-mood.mjs").MoodState;
  writeMood: (threadId: string, state: unknown) => void;
  forgetThreadMood: (threadId: string) => void;
  bumpMood: (threadId: string, signal: string) => void;
  runtimeStateRef: React.RefObject<{ model: string; effort: string; sandbox: string; approval: string; }>;
  adoptedRevRef: React.RefObject<Record<string, number>>;
  dispatchInfo: { description: string; targets: DispatchTargetEntry[]; };
  setDispatchInfo: React.Dispatch<React.SetStateAction<{ description: string; targets: DispatchTargetEntry[]; }>>;
  delegateRecords: Record<string, DelegateRecordEntry>;
  setDelegateRecords: React.Dispatch<React.SetStateAction<Record<string, DelegateRecordEntry>>>;
  dispatchOwnerId: string | null;
  setDispatchOwnerId: React.Dispatch<React.SetStateAction<string | null>>;
  refreshDispatchOwner: () => Promise<void>;
  threadRole: { restricted: boolean; label?: string | undefined; };
  setThreadRole: React.Dispatch<React.SetStateAction<{ restricted: boolean; label?: string | undefined; }>>;
  refreshThreadRole: (threadId?: string | undefined) => Promise<void>;
  delegateRecordsRef: React.RefObject<Record<string, DelegateRecordEntry>>;
  dispatchInfoRef: React.RefObject<{ description: string; targets: DispatchTargetEntry[]; }>;
  refreshDispatchInfo: () => Promise<void>;
  refreshDelegateRecords: () => Promise<void>;
  dispatchBusy: boolean;
  setDispatchBusy: React.Dispatch<React.SetStateAction<boolean>>;
  delegateLiveRuns: Record<string, DelegateRecordEntry>;
  setDelegateLiveRuns: React.Dispatch<React.SetStateAction<Record<string, DelegateRecordEntry>>>;
  delegatedPopupId: string;
  setDelegatedPopupId: React.Dispatch<React.SetStateAction<string>>;
  delegateRailTimersRef: React.RefObject<Map<string, NodeJS.Timeout>>;
  dispatchTick: number;
  setDispatchTick: React.Dispatch<React.SetStateAction<number>>;
  activeDispatch: import("../../../lib/thread-runtime.mjs").DispatchConfig;
  dispatchHolderName: string | null;
  taskRunning: boolean;
  lastTurnOfThread: import("../../../lib/turn.ts").Turn | undefined;
  turnFinalizing: boolean;
  runActivity: "" | "正在执行命令" | "正在编辑文件" | "正在深度思考" | "正在搜索网页" | "正在调用工具" | "正文已完整，等待模型收尾" | "正在生成回复";
  runPhrase: string;
  setRunPhrase: React.Dispatch<React.SetStateAction<string>>;
  runActivityRef: React.RefObject<string>;
  finalizePhraseRef: React.RefObject<boolean>;
  applyDispatch: (next: { enabled: boolean; expert: boolean; team: boolean; subagent: boolean; }, opts?: { takeOver?: boolean | undefined; } | undefined) => Promise<void>;
  admitThreadRuntime: (id: string, runtime: unknown, opts?: { conflict?: boolean | undefined; fromRemote?: boolean | undefined; } | undefined) => void;
  syncThreadRuntimeWithMain: (id: string) => Promise<void>;
  loadBaseInstructions: () => Promise<string>;
  buildSessionScope: (threadId: string, override?: { model?: unknown; effort?: unknown; sandbox?: unknown; approval?: unknown; provider?: unknown; } | undefined) => Promise<{ signature: string; collaborationMode: Record<string, unknown>; } | null>;
  pushSessionScope: (threadId: string, override?: { model?: unknown; effort?: unknown; sandbox?: unknown; approval?: unknown; provider?: unknown; } | undefined) => Promise<void>;
  applyGlobalModelChoice: (nextId: string) => void;
  savedEffortFor: (model: string | undefined) => string;
  rememberEffortFor: (model: string | undefined, value: string) => void;
  chooseModel: (value: string) => Promise<void>;
  migrateThreadToProvider: (threadId: string, target: { provider: string; model: string; name: string; baseUrl: string; wireApi?: string | undefined; }) => Promise<{ ok: boolean; error?: string | undefined; }>;
  alignThreadToProvider: (threadId: string, target: { provider: string; model: string; name: string; baseUrl: string; wireApi?: string | undefined; }, opts?: { reason?: "error" | "open" | "send" | "switch" | undefined; silent?: boolean | undefined; } | undefined) => Promise<"same" | "migrated" | "relayed" | "failed">;
  applyPendingRestart: (pendingOverride?: { provider: string; model: string; label: string; prevProvider: string; prevModel: string; } | null | undefined) => Promise<void>;
  cancelPendingRestart: () => Promise<void>;
  updateThreadSettings: (values: Record<string, unknown>) => Promise<void>;
  pushThreadPermissions: (id: string, sandboxValue: string, approvalValue: string) => Promise<void>;
  changeApproval: (value: string) => void;
  changePermissionMode: (value: string) => void;
  globalPermApproval: string;
  setGlobalPermApproval: React.Dispatch<React.SetStateAction<string>>;
  applyGlobalPermissionMode: (value: string) => void;
  changeSandbox: (value: string) => void;
  applyEffort: (value: string) => void;
  changeEffort: (value: string) => void;
  changePersonality: (value: string) => void;
  copyMessage: (text: string) => Promise<void>;
  copyThreadReferenceId: (target: { id: string; }) => Promise<void>;
  loadThreadReference: (id: string) => Promise<import("../../../lib/user-refs.ts").ThreadReferencePayload | null>;
  resolveThreadReferences: (text: string, currentThreadId?: string | undefined) => Promise<{ text: string; blocks: string; referenced: boolean; }>;
  editResend: (turnId: string, item: import("../../../lib/thread-item.ts").ThreadItem) => Promise<void>;
  copyImage: (path: string) => Promise<void>;
  quoteMessage: (text: string) => void;
  cancelQuote: () => void;
  addContextItem: (item: { id: string; role: "用户" | "Codex"; text: string; }) => void;
  removeContextItem: (id: string) => void;
  addSkillReference: (skill: { name: string; description: string; }) => void;
  onPromptChange: (value: string) => void;
  forkFromTurn: (turnId: string) => Promise<void>;
  exportThreadsBackup: (threadIds?: string[] | undefined) => Promise<void>;
  importThreadsBackup: () => Promise<void>;
  exportThreadsMarkdown: (threadIds?: string[] | undefined) => Promise<void>;
  forkThreadFromSidebar: (entry: import("../../app-view/types.ts").Thread) => Promise<void>;
  importConversationMarkdown: () => Promise<void>;
  startNewThread: () => void;
  runSlashCommand: (value: string) => Promise<boolean>;
  startReview: (instructions: string) => void;
  chooseWorkspace: () => Promise<void>;
  chooseImages: () => Promise<void>;
  chooseFiles: () => Promise<void>;
  refreshMarketSkills: (category?: string, query?: string, page?: number) => Promise<void>;
  refreshMarketPlugins: (category?: string, query?: string, page?: number) => Promise<void>;
  refreshPluginsPage: () => Promise<void>;
  installMarketPlugin: (plugin: PluginMarketEntry) => Promise<void>;
  installMarketSkill: (skill: MarketSkillEntry) => Promise<void>;
  toggleSkillEnabled: (entry: LocalSkillEntry) => Promise<void>;
  saveConnector: (draft?: ConnectorDraft) => Promise<void>;
  installMcpServer: (entry: import("../../../lib/skillhub-mcp.ts").SkillHubMcpEntry) => void;
  startConnectorOAuth: () => Promise<void>;
  saveConnectorFromTemplate: (template: ConnectorTemplate) => Promise<void>;
  removeConnector: (id: string) => Promise<void>;
  setConnectorEnabled: (connector: ConnectorEntry, enabled: boolean) => Promise<void>;
  batchSetConnectorsEnabled: (ids: string[], enabled: boolean) => Promise<void>;
  setMcpServerEnabled: (name: string, enabled: boolean) => Promise<void>;
  batchSetMcpServersEnabled: (ids: string[], enabled: boolean) => Promise<void>;
  setMcpToolPermission: (server: string, tool: string, mode: "deny" | "ask" | "allow" | null) => Promise<void>;
  refreshSubAgents: () => Promise<void>;
  saveSubAgent: (draft: SubAgentEntry) => Promise<void>;
  toggleSubAgentEnabled: (agent: SubAgentEntry) => Promise<void>;
  deleteSubAgent: (id: string) => Promise<void>;
  openNewSubAgent: () => void;
  openEditSubAgent: (agent: SubAgentEntry) => void;
  refreshExpertTeams: () => Promise<void>;
  saveExpertTeam: (draft: ExpertTeamConfig) => Promise<void>;
  toggleExpertTeamEnabled: (team: ExpertTeamConfig) => Promise<void>;
  deleteExpertTeam: (teamId: string) => Promise<void>;
  resetExpertTeams: () => Promise<void>;
  openNewExpertTeam: () => void;
  openEditExpertTeam: (team: ExpertTeamConfig) => void;
  chooseTeamCwd: (teamId: string) => Promise<void>;
  clearTeamCwd: (teamId: string) => void;
  startMemberDirectSession: (team: ExpertTeamConfig, member: ExpertTeamMember) => Promise<void>;
  startTeamSession: (team: ExpertTeamConfig, task: string) => Promise<void>;
  runTeamMember: (toolArgs: any, leadThreadId: string) => Promise<{ ok: boolean; name: string; profession: string; output: string; }>;
  invokeTeamMember: (toolArgs: any, threadId: string, respondEventId: string | number) => Promise<void>;
  invokeTeamPhase: (tasks: any[], threadId: string, respondEventId: string | number) => Promise<void>;
  importSkill: () => Promise<void>;
  removeLocalSkill: (entry: { folder?: string | undefined; name: string; description?: string | undefined; }) => Promise<void>;
  pasteImage: (fallbackPath?: string) => Promise<void>;
  showEnhanceHint: () => void;
  dismissEnhanceHint: () => void;
  runPromptEnhance: () => Promise<void>;
  cancelPromptEnhance: () => void;
  promptIncludesBackup: (current: string, backup: string) => boolean;
  insertComposerAttachments: (kind: "file" | "image", paths: string[]) => void;
  insertComposerImages: (paths: string[]) => void;
  insertComposerFiles: (paths: string[]) => void;
  pasteLongText: (text: string) => Promise<void>;
  resumeThreadLight: (params: { threadId: string; sandbox?: string | undefined; approvalPolicy?: string | undefined; dynamicTools?: any[] | undefined; }, turnBudget?: number) => Promise<any>;
  loadEarlierTurns: (id: string) => Promise<void>;
  onTimelineScroll: (event: React.UIEvent<HTMLDivElement, UIEvent>) => void;
  jumpToTurnInWindow: (turnId: string) => void;
  popoutCurrentThread: (threadId: string) => Promise<void>;
  rememberScrollPosition: (id: string) => void;
  recallScrollOffset: (id: string) => number | null;
  openThread: (id: string, freshThread?: import("../../app-view/types.ts").Thread | null | undefined) => Promise<void>;
  cascadeTeamCluster: (id: string, action: "archive" | "delete") => Promise<number>;
  archiveThread: (id: string) => Promise<void>;
  renameThread: (id: string, value: string) => Promise<void>;
  clearCurrentConversation: () => Promise<void>;
  unarchiveThread: (id: string) => Promise<void>;
  deleteThreadCore: (id: string) => Promise<void>;
  deleteThread: (id: string) => Promise<void>;
  releaseDispatchHolder: () => Promise<void>;
  deleteThreadsByCwd: (cwd: string) => Promise<void>;
  buildDynamicTools: () => Promise<any[]>;
  createEmptyThread: () => Promise<import("../../app-view/types.ts").Thread | null>;
  send: (event?: React.FormEvent<Element> | undefined) => Promise<void>;
  handleLogin: (info: { provider: string; name: string; baseUrl: string; apiKey: string; model: string; username?: string | undefined; }) => Promise<boolean>;
  handleSkip: () => Promise<void>;
  MODEL_CONFIGURED_KEY: "model-configured-v1";
  markModelConfigured: () => void;
  hadModelConfigured: () => boolean;
  quickSetup: (info: { provider: string; name: string; baseUrl: string; apiKey: string; }) => Promise<void>;
  relayQuickLogin: (info: { baseUrl: string; email: string; password: string; }) => Promise<void>;
  handleLogout: () => Promise<void>;
  confirmPlanExecution: () => void;
  cancelPlanExecution: () => void;
  submitPlanFeedback: () => void;
  stopGoalLoop: () => void;
  interrupt: () => Promise<void>;
  onComposerKeyDown: (event: React.KeyboardEvent<HTMLDivElement>) => void;
  closePanelTab: (key: string) => void;
  openPanelTab: (key: string, name: string) => void;
  turnWindow: Record<string, number>;
  setTurnWindow: React.Dispatch<React.SetStateAction<Record<string, number>>>;
  turnWindowRef: React.RefObject<Record<string, number>>;
  loadingEarlierRef: React.RefObject<Set<string>>;
  earlierLoadingId: string | null;
  setEarlierLoadingId: React.Dispatch<React.SetStateAction<string | null>>;
  userScrolledRef: React.RefObject<boolean>;
  expandTurnWindow: (id: string, count: number) => void;
  collapseTurnWindow: (id: string) => void;
  allItems: import("../../../lib/thread-item.ts").ThreadItem[];
  isEmpty: boolean;
  switchingMeta: import("../../app-view/types.ts").Thread | null | undefined;
  paletteHandlersRef: React.RefObject<{ startNewThread: () => void; chooseWorkspace: () => Promise<void>; setSettingsPage: React.Dispatch<React.SetStateAction<import("../../app-view/types.ts").SettingsPage>>; setSettingsOpen: React.Dispatch<React.SetStateAction<boolean>>; setRightOpen: React.Dispatch<React.SetStateAction<boolean>>; openPanelTab: (key: string, name: string) => void; openThread: (id: string, freshThread?: import("../../app-view/types.ts").Thread | null | undefined) => Promise<void>; openFile: (path: string) => Promise<void>; }>;
  paletteSections: { group: string; rows: any[]; }[];
  fileTruncated: boolean;
  usage: any;
  lastUsage: any;
  completedTurns: import("../../../lib/turn.ts").Turn[];
  latestCompletedTurn: import("../../../lib/turn.ts").Turn | undefined;
  stats: import("../../../lib/usage-stats.ts").UsageStats;
  activeFlags: string[];
  waitingForApproval: boolean;
  waitingForInput: boolean;
  activeThreadRunning: boolean;
  enhanceAnchorVisible: boolean;
  activeThreadMemberRunning: { teamId: string; memberName: string; } | null;
  activeMemberTeam: ExpertTeamConfig | null;
  activeMember: ExpertTeamMember | null;
  activityLabel: string;
  railTeamId: string;
  railTeam: ExpertTeamConfig | null;
  railRuns: TeamMemberRunRecord[];
  railRunningByMember: Record<string, TeamMemberRunRecord>;
  railLastByMember: Record<string, TeamMemberRunRecord>;
  popupRun: TeamMemberRunRecord | null;
  historyMemberRuns: TeamMemberRunRecord[];
  delegatedRailRuns: DelegateRecordEntry[];
  delegatedPopupRun: DelegateRecordEntry | null;
  recentCompaction: boolean;
  saveInlineRename: () => void;
  earlyView: React.JSX.Element | null;
  topbarActionsNode: React.JSX.Element;
  /* ── 收藏夹（09-24，手写登记；真相源在主进程 userData/favorites.json，这里是镜像）──
     ⛔ 【93】会用「当前 parts 重新推断」比对本文件 ⇒ 这几个签名必须与 part07/03-seg 的
     实际声明逐字一致（改一边就红）。 */
  favorites: FavoriteItem[];
  setFavorites: React.Dispatch<React.SetStateAction<FavoriteItem[]>>;
  favoritesBusy: boolean;
  setFavoritesBusy: React.Dispatch<React.SetStateAction<boolean>>;
  refreshFavorites: () => Promise<FavoriteItem[]>;
  favoriteFromMessage: (request: FavoriteRequest) => Promise<void>;
  addFavoriteItem: (input: Partial<FavoriteItem>) => Promise<FavoriteItem | null>;
  updateFavoriteItem: (id: string, patch: Partial<FavoriteItem>) => Promise<void>;
  removeFavoriteItems: (ids: string[]) => Promise<number>;
  insertFavorite: (item: FavoriteItem) => void;
  sendFavorite: (item: FavoriteItem) => Promise<void>;
  favoriteToMemory: (ids: string[], scope: MemoryLayerScope) => Promise<FavoritesToMemoryResult>;
}
