/** 连接器（MCP）（从 src/App.tsx 原样搬来，内容未改）。域公开面见 ./index.ts */
import { Link2, X, TerminalSquare, Globe2, Info, Check, Zap, KeyRound, CircleCheck, AlertTriangle } from "lucide-react";
import { Spinner } from "../../components/CardShell";

export function ConnectorSetupModal({ draft, secret, saving, onDraftChange, onSecretChange, onClose, onSave }: { draft: ConnectorDraft; secret: string; saving: boolean; onDraftChange: (draft: ConnectorDraft) => void; onSecretChange: (value: string) => void; onClose: () => void; onSave: (draft: ConnectorDraft) => void }) {
  const valid = Boolean(draft.name.trim() && (draft.transport === "stdio" ? draft.command?.trim() : draft.url?.trim()));
  const changeTransport = (transport: ConnectorDraft["transport"]) => onDraftChange({ ...draft, transport });
  const save = () => onSave({ ...draft, secrets: secret.trim() ? { MCP_TOKEN: secret.trim() } : {} });
  return <div className="modal-backdrop connector-modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="connector-setup-modal" role="dialog" aria-modal="true" aria-label="添加 MCP 连接器">
    <header><div className="connector-setup-title"><span><Link2 size={17} /></span><div><strong>添加 MCP 连接器</strong><p>填写服务提供方给出的连接信息，保存后会自动重启引擎并校验状态。</p></div></div><button className="icon-button relay-modal-close" title="关闭" onClick={onClose}><X size={16} /></button></header>
    <div className="connector-setup-steps"><span className="active">1 选择方式</span><i /><span>2 填写连接</span><i /><span>3 保存并验证</span></div>
    <div className="connector-transport-cards"><button type="button" className={draft.transport === "stdio" ? "active" : ""} onClick={() => changeTransport("stdio")}><TerminalSquare size={18} /><b>本地命令</b><small>适用于 npm、uvx、Docker 或已安装的 MCP 服务。</small></button><button type="button" className={draft.transport === "streamable_http" ? "active" : ""} onClick={() => changeTransport("streamable_http")}><Globe2 size={18} /><b>远程 HTTP</b><small>适用于服务商提供的 HTTPS MCP 地址和令牌。</small></button></div>
    <div className="connector-form"><label><span>连接器名称 <em>必填</em></span><input autoFocus value={draft.name} onChange={(event) => onDraftChange({ ...draft, name: event.target.value })} placeholder="例如：GitHub MCP" /></label>{draft.transport === "stdio" ? <><label><span>启动命令 <em>必填</em></span><input value={draft.command ?? ""} onChange={(event) => onDraftChange({ ...draft, command: event.target.value })} placeholder="例如：npx" /></label><label><span>命令参数 <small>可选，按空格分隔</small></span><input value={(draft.args ?? []).join(" ")} onChange={(event) => onDraftChange({ ...draft, args: event.target.value.trim() ? event.target.value.trim().split(/\s+/) : [] })} placeholder="例如：-y @modelcontextprotocol/server-github" /></label><div className="connector-example"><Info size={14} /><span>示例：<code>npx -y @modelcontextprotocol/server-github</code></span></div></> : <><label><span>MCP 服务地址 <em>必填</em></span><input value={draft.url ?? ""} onChange={(event) => onDraftChange({ ...draft, url: event.target.value })} placeholder="https://service.example.com/mcp" /></label><div className="connector-example"><Info size={14} /><span>请粘贴服务方提供的完整 HTTPS MCP 地址，不是官网主页。</span></div></>}<label><span>访问令牌 <small>可选，系统会加密保存</small></span><input value={secret} type="password" onChange={(event) => onSecretChange(event.target.value)} placeholder="没有令牌可先留空" /></label></div>
    <footer><button className="secondary-setting" onClick={onClose}>取消</button><button className="primary-setting" disabled={!valid || saving} onClick={save}>{saving ? <Spinner /> : <Check size={15} />}保存并验证</button></footer>
  </section></div>;
}

export function ConnectorTemplateModal({ template, values, saving, oauth, onChange, onClose, onSave, onOAuth }: { template: ConnectorTemplate; values: Record<string, string>; saving: boolean; oauth: ConnectorOAuthEvent | null; onChange: (values: Record<string, string>) => void; onClose: () => void; onSave: () => void; onOAuth: () => void }) {
  const invalid = template.fields.filter((field) => !field.optional && !values[field.key]?.trim());
  const oauthBusy = oauth?.phase === "waiting";
  return <div className="modal-backdrop connector-modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget && !oauthBusy) onClose(); }}><section className="connector-setup-modal" role="dialog" aria-modal="true" aria-label={`配置 ${template.name}`}>
    <header><div className="connector-setup-title"><span><Link2 size={17} /></span><div><strong>配置 {template.name}</strong><p>{template.summary}</p></div></div><button className="icon-button relay-modal-close" title="关闭" onClick={onClose}><X size={16} /></button></header>
    <div className="connector-template-vendor"><Zap size={13} /><span>{template.vendor}</span><small>{template.transport === "stdio" ? "本地命令 · stdio" : "远程服务 · HTTP MCP"}</small></div>
    <div className="connector-form">{template.fields.map((field, index) => <label key={field.key}><span>{field.label}{field.optional ? <small> 可选</small> : <em> 必填</em>}</span><input autoFocus={index === 0} value={values[field.key] ?? ""} type={field.secret ? "password" : "text"} onChange={(event) => onChange({ ...values, [field.key]: event.target.value })} placeholder={field.placeholder} />{field.hint && <small className="field-hint">{field.hint}</small>}</label>)}
      {template.oauth && <div className="connector-oauth-zone"><div className="connector-oauth-head"><KeyRound size={14} /><strong>OAuth 授权</strong><small>跳转官方授权页，授权完成即连接</small></div>{template.oauthNote && <p className="field-hint">{template.oauthNote}</p>}
        {oauth?.phase === "waiting" && <div className="oauth-status waiting"><Spinner /><span>{oauth.message}</span>{oauth.authorizeUrl && <a className="oauth-open-link" href={oauth.authorizeUrl} target="_blank" rel="noreferrer">没自动打开？点此打开授权页</a>}</div>}
        {oauth?.phase === "authorized" && <div className="oauth-status ok"><CircleCheck size={15} /><span>{oauth.message}</span></div>}
        {oauth?.phase === "failed" && <div className="oauth-status fail"><AlertTriangle size={15} /><span>{oauth.message}</span></div>}
      </div>}
      <div className="connector-example"><Info size={14} /><span>{template.transport === "stdio" ? "填写后写入本机 Codex 配置（命令行参数或环境变量），密钥仅保存在本机。" : "密钥走系统加密存储，经 Authorization 头注入远程 MCP。"} <a href={template.helpUrl} target="_blank" rel="noreferrer" onClick={(event) => event.stopPropagation()}>如何获取凭据 ↗</a></span></div></div>
    <footer><button className="secondary-setting" onClick={onClose}>取消</button><button className="secondary-setting" disabled={invalid.length > 0 || saving || oauthBusy} onClick={onSave}>{saving ? <Spinner /> : <Check size={15} />}保存并验证</button>{template.oauth && <button className="primary-setting" disabled={invalid.length > 0 || saving || oauthBusy} onClick={onOAuth}>{oauthBusy ? <Spinner /> : <KeyRound size={15} />}{oauth?.phase === "authorized" ? "重新授权" : "授权连接"}</button>}</footer>
  </section></div>;
}
